### ISSUE TITLE
Create-React-App support?

### ISSUE THREAD

**Issue by Kotoriii** [amsul/pickadate.js#1008]
Hey there,

I loved this library for standard JQuery projects and I'm now trying to make it work with Create-React-App. However, I have already trouble importing the library in my files.

On `picker.js` I tried removing the `AMD` config and just writing the opening lines like this

```
import jQuery from 'jquery';

(function ( factory ) {

    // Node.js/browserify.
    if ( typeof exports == 'object' )
        module.exports = factory( require('jquery') )

    // Browser globals.
    else this.Picker = factory( jQuery )
```
However, I now get a `TypeError: Cannot set property 'Picker' of undefined` error. Also had to explicitly declare a variable on line 536. But now I cannot get past this part. 

If you made this work with Create-React-App, I'd appreciate your input. Thanks!

**Comment by Kotoriii** [comment]
After some tinkering around, removing `else this.Picker = factory( jQuery )` made the import work. Now, I only need to make the plugin work :')

**Comment by Tusko** [comment]
`else this.Picker = factory( jQuery )` doesn't work :(
I've changed it to `else window.Picker = factory( jQuery )`
