### ISSUE TITLE
"Never use the yy rule in the formatSubmit option." - Why?

### ISSUE THREAD

**Issue by shainanigans** [amsul/pickadate.js#1015]
I don't have an issue per se, but a question. In the [docs](http://amsul.ca/pickadate.js/date/#formatting-rules) it says "Never use the yy rule in the formatSubmit option." Why is this a bad idea?

**Comment by cristiammercado** [comment]
I think it's because it can cause confusion between the days and/or months and the years ending between 00 and 12

**Comment by DanielRuf** [comment]
Because `formatSubmit` is the value which is sent to your backend where `date` is in the format `dd-mm-yyyy`.
