### ISSUE TITLE
How remove pickadate from element?

### ISSUE THREAD

**Issue by AdrianKuriata** [amsul/pickadate.js#1021]
Hi, this is possible remove pickadate from element? I have a troubles with bootstrap modals and i need after close modal remove pickadate from input, because i using dynamic load data to modals and after render pickadate normall i can't change data-value in datepicker.

I found #98 - but here is not a solution same like in #119

**Comment by gianlucagiacometti** [comment]
Same problem here, any solutions?

**Comment by AdrianKuriata** [comment]
@gianlucagiacometti Change picker, i did it and everything is good.

**Comment by DanielRuf** [comment]
Sorry but thus is not how someone solves a problem. One solution would be to clone the initial component / HTML element and replace the current picker with it and so on.

**Comment by DanielRuf** [comment]
Sorry but this is not how someone solves a problem. One solution would be to clone the initial component / HTML element and replace the current picker with it and so on.

**Comment by gianlucagiacometti** [comment]
@DanielRuf  I solved more or less as you said, deleting and re-adding the input from DOM, re-attaching the pickadate. It works also in modals. I'm happy with this picker and I'm also using MDBootstrap in my projects.
