### ISSUE TITLE
Remove classes (css) from Pickadate.js in Materialize

### ISSUE THREAD

**Issue by LeonardJAvi** [amsul/pickadate.js#1022]
Inconsistent with pickdate I require to remove a css classes from the calendar. The classes I want to disable are: 1) .picker__day - highlighted 2) .picker__day.picker__day - today
In order to remove the color (green) to the present day.

**Comment by DanielRuf** [comment]
So far we have moved to an own implementation in Materialize v1 and rewrote most parts.
