### ISSUE TITLE
Date Range

### ISSUE THREAD

**Issue by Lieber7** [amsul/pickadate.js#1026]
Hello, there is an option to make a range? I mean that I will press on a date and then on other date and in the input will be the range? like here: http://t1m0n.name/air-datepicker/docs/ (search Range of dates).
In addition, I'm looking for the option to add predefined dates. for example today, yesterday, last 7 days, last 30 days etc.
I really like your component, especially on the mobile. Good job! 👍 
Thank you!

**Comment by DanielRuf** [comment]
See https://github.com/amsul/pickadate.js/issues/446
