### ISSUE TITLE
Some text cut when selectYears: true or selectMonths: true

### ISSUE THREAD

**Issue by keyurpatel30** [amsul/pickadate.js#1040]
I am using Chrome to test & check.

Some of the dropdown selected item display text is cut from the bottom as shown in the images below.

Example image from [the website](http://amsul.ca/pickadate.js/date/#selectors) (only if dropdown selectors are set to true): 
![image](https://user-images.githubusercontent.com/10952555/35255304-594b1c04-0029-11e8-815b-f86e9dcf4ad7.png)

Somehow looks even worse on the website I use it on:

![image](https://user-images.githubusercontent.com/10952555/35255327-74e71238-0029-11e8-8ea2-e74c092459b0.png)

and 

![image](https://user-images.githubusercontent.com/10952555/35255338-83e6a1a4-0029-11e8-93ed-080fe88d2695.png)

**Comment by keyurpatel30** [comment]
Worked like a charm, thank you!

**Comment by rrikesh** [comment]
I get the bug on the dropdown selectors example - http://amsul.ca/pickadate.js/date/#selectors - only on Firefox Mac. Looks good on Chrome and Safari.

**Comment by clearwaterstream** [comment]
I do this:

.picker__select--month,
.picker__select--year {
  height: auto;
}
