### ISSUE TITLE
bug on march 1st 2018

### ISSUE THREAD

**Issue by DanielRuf** [amsul/pickadate.js#1060]
It seems there is a bug regarding 29th Feb / 1st Mar. The max unit test fails in this case.

We have to check this and fix the calculation.

How to reproduce: change the date of the system clock and run the unit tests.

**Comment by DanielRuf** [comment]
@amsul I think this does not occur in v5.

**Comment by amsul** [comment]
I guess it's safe to close then?

In v5, we don't yet have extensive testing on dates rendering (especially around time zones and daylight savings).
