### ISSUE TITLE
activeElement is breaking $.contains() method

### ISSUE THREAD

**Issue by Amitesh** [amsul/pickadate.js#1074]
https://github.com/amsul/pickadate.js/blob/f93866d83d9fcc58d1c8f664b9affe8a2751aaea/lib/picker.js#L732

```javascript
activeElement = activeElement && ( activeElement.type || activeElement.href )
```
In the above statement, if the `activeElement` is button or anchor then it will return `string` type of value and `$.contains()` is expecting DOM type of parameter.

[https://api.jquery.com/jquery.contains/](https://api.jquery.com/jquery.contains/)

Error message:

```
jquery.1.7.0.js:5306 Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
    at Function.Sizzle.contains (jquery.1.7.0.js:5306)
    at HTMLButtonElement.<anonymous> (picker.js:732)
    at HTMLDivElement.dispatch (jquery.1.7.0.js:3319)
    at HTMLDivElement.eventHandle (jquery.1.7.0.js:2925)
```

**Comment by Amitesh** [comment]
Hi @DanielRuf ,

I have also observe it is coming with lower version of jQuery (1.7.0) which is bundled with the [3.5.6](http://github.com/amsul/pickadate.js/archive/3.5.6.zip) archive on page [http://amsul.ca/pickadate.js/](http://amsul.ca/pickadate.js/). I have tried same with jQuery 2.1.3 it works well.

[Sample code on CodePen - https://codepen.io/amitesh/pen/PRLwvQ](https://codepen.io/amitesh/pen/PRLwvQ)

I have also raised a [PR](https://github.com/amsul/pickadate.js/pull/1075) for same.

Thanks.

**Comment by DanielRuf** [comment]
> I have tried same with jQuery 2.1.3 it works well.

So this is an issue with jQuery and not Pickadate then.
