### ISSUE TITLE
onSet - passing the focus to next field

### ISSUE THREAD

**Issue by moseleyi** [amsul/pickadate.js#1085]
Just a question whether it's possible. When somebody selects a date pressing an enter I would like to delegate the focus to the next field without the necessity of pressing tab or clicking to another field. 

Is it possible to get the context of the field that triggers the datepicker in `onSet` function? At the moment I only have one datepicker on the page, which makes it easy to just call it `$(".datepicker")` but what if I have many?

--- edit

Actually I found it by accessing `this.$node` but do you think it would be easier to have it in context so it's clearer?

After few tries I can't seem to be able to trigger the focus, is it because onSet will be earlier than manually returning focus to the datepicker element?

**Comment by DanielRuf** [comment]
.on('keyup') + event.keycode / which +e.target is what you need.

**Comment by DanielRuf** [comment]
Also don't foget to wrap the trigger in `setTimeout`.

**Comment by moseleyi** [comment]
Thanks I got it to work with using onClose rather than onSet
