### ISSUE TITLE
Datepicker Editable Broken

### ISSUE THREAD

**Issue by craigpotter** [amsul/pickadate.js#1087]
Hi, 

`	
	$('.datepicker').pickadate({
	  editable: true
	});
`
Clicking on the input does nothing. 

I can provide a codepen if required however it is also broken on the documentation [here](http://amsul.ca/pickadate.js/date/#editable)

**Comment by amsul** [comment]
@craigpotter yup..and if you read further down, it says:

> An important thing to note here is that this disables keyboard bindings on the input element, such as arrow keys opening the picker. You will have to add your own bindings as you see fit.

🙂

**Comment by p8** [comment]
oops, sorry :)

**Comment by craigpotter** [comment]
@amsul I didn't think mouse clicks would class as keyboard bindings

**Comment by amsul** [comment]
I actually misread the initial report. I'm actually seeing a very odd behavior in the [docs](http://amsul.ca/pickadate.js/date/#editable) now.

@DanielRuf try opening the picker and then closing it again. It doesn't seem to close.

**Comment by DanielRuf** [comment]
Hm, is it due to the latest hitfix (bisect)? If so we should revert/patch it.

**Comment by DanielRuf** [comment]
Hm, is it due to the latest hotfix (bisect)? If so we should revert/patch it.

**Comment by DanielRuf** [comment]
Hm, is it due to the latest hotfix (bisect)? If so we should revert/patch it.

**Comment by DanielRuf** [comment]
https://github.com/amsul/pickadate.js/pull/1145

@colinhowe

Can you add unit tests for this and test the previous release?

**Comment by colinhowe** [comment]
That's an odd behaviour. I'll take a look as I definitely wouldn't have tested against the editable variant.

**Comment by colinhowe** [comment]
Using the codepen from @p8 suggests the bug was introduced between 3.6.0 and 3.6.1

**Comment by p8** [comment]
yes, I noticed the problem when upgrading from e528acc to 3.6.2

**Comment by DanielRuf** [comment]
Hm, between .0 and .1 is just the Chrome 73 workaround.

https://github.com/amsul/pickadate.js/compare/3.6.0...3.6.1

**Comment by DanielRuf** [comment]
It's basically because of https://github.com/amsul/pickadate.js/blob/master/lib/picker.js#L363

I'll test if I have to remove my workaround.

**Comment by DanielRuf** [comment]
Seems so:
https://codepen.io/DanielRuf/pen/YMLBqo

Sorry for that, I'll prepare a fix.

**Comment by amsul** [comment]
It should be fixed on master now with this fix: https://github.com/amsul/pickadate.js/pull/1158

**Comment by DanielRuf** [comment]
Closing as fixed.

**Comment by AstghikMirijanyan** [comment]
$('.datepicker').on('mousedown',function(event){
    event.preventDefault();
});

**Comment by DanielRuf** [comment]
> $('.datepicker').on('mousedown',function(event){
> event.preventDefault();
> });

Hi @AstghikMirijanyan,

did you already try the latest release? It should be fixed in 3.6.4.
See http://amsul.ca/pickadate.js/date/#editable

**Comment by AstghikMirijanyan** [comment]
hello this code I worked fine and the calendar opens without problems

**Comment by DanielRuf** [comment]
> hello this code I worked fine and the calendar opens without problems

Hi, can you clarify?
Does the current 3.6.4 release work for you?

**Comment by AstghikMirijanyan** [comment]
> > hello this code I worked fine and the calendar opens without problems
> 
> Hi, can you clarify?
> Does the current 3.6.4 release work for you?

I am using materialize.js and there were problems, 
but pickadate.js did not connect

**Comment by DanielRuf** [comment]
> I am using materialize.js and there were problems,
> but pickadate.js did not connect

Not completely sure what you mean. Materialize provides its own customized version of pickadate. You would have to directly change the files in Materialize.
