### ISSUE TITLE
Datepicker Not Working for HTTPS connection

### ISSUE THREAD

**Issue by Srikanth8798** [amsul/pickadate.js#1088]
Amsul datepicker does not work if your connection is secure , it works only for insecure connection for http

**Comment by DanielRuf** [comment]
Please provide more details and check your browser console for errors.

**Comment by Srikanth8798** [comment]
![image](https://user-images.githubusercontent.com/40567554/42491585-00ee638e-8433-11e8-8fa4-61b7dcb34e5e.png)

**Comment by Srikanth8798** [comment]
Included all files but still the error exists

**Comment by Srikanth8798** [comment]
![image](https://user-images.githubusercontent.com/40567554/42491626-36f3d392-8433-11e8-9d50-12a7cd6a03ec.png)

**Comment by DanielRuf** [comment]
Please check the browser console and network requests in the devtools.

**Comment by Srikanth8798** [comment]
![image](https://user-images.githubusercontent.com/40567554/42493714-b293dbd4-843b-11e8-8615-ac3372c9a7e9.png)

How to solve this

**Comment by Srikanth8798** [comment]
Error Facing 

was loaded over HTTPS, but requested an insecure script 'http://amsul.ca/pickadate.js/vendor/pickadate/lib/picker.js'. This request has been blocked; the content must be served over HTTPS.

please suggest any methods asap

**Comment by Srikanth8798** [comment]
![image](https://user-images.githubusercontent.com/40567554/42493799-ed5686c2-843b-11e8-9d93-3e81cd255de0.png)

**Comment by DanielRuf** [comment]
Please download / install the release with npm or manually and do not use amsul.ca as CDN.
