### ISSUE TITLE
whenever the pickadate opens it scrolls back to the top of the browser.

### ISSUE THREAD

**Issue by moecantplay** [amsul/pickadate.js#1095]
I'm using v3.5.6,
I tested this on a Macbook Pro and iPhone.
On the Macbook Pro the problem exists on Google Chrome, no problems on Safari.
but on iPhone the problem exists on both Google Chrome and Safari.

I tried looking around for the solution but can't seem to find one.
Appreciate the help in advance, thanks.

**Comment by Janny2018** [comment]
I have the similar problem in using .pickadate() to show the canlendar,
the date from right to left. 
the problem exists on both Google Chrome and IE 11 
![20180811-1](https://user-images.githubusercontent.com/42291583/43989720-d840a600-9d81-11e8-945b-7de8cbe74dc1.JPG)

**Comment by DanielRuf** [comment]
Can you provide some codepen?

**Comment by moecantplay** [comment]
i found what was causing it to scroll back up..
weirdly.. it's because of my body having an '_overflow-x: hidden;_'.
So i removed that and now it's no longer scrolling back up but i have a different issue now where everytime i switch tabs the datepicker will automatically opened.
I tried adding `onClose: function() {
			$('.datepicker').blur();
		}` but no luck for me.. anything im missing?

**Comment by Janny2018** [comment]
Dear  Daniel,
Sorry for my late reply,
I can not figure out what happened,
I attach two files , one is my screen shot , one is after the screen show
up in the browser, I Press F12 to copy the the content in <body> tag
Thanks a lot.  Wish you can help me to solve the problem

Best Regards
Janny

Gervin Sean <notifications@github.com> 於 2018年8月13日 週一 上午10:28寫道：

**Comment by DanielRuf** [comment]
Without a proper codepen we can not reproduce / test this.

**Comment by Janny2018** [comment]
I have attached two files in last email , is it not enough ?
the code  is part of an asp.net MVC project (semi-finished product),  and
the project will access database,
I don't know what should I provide ?  the View file(*.cshtml file) ?

Daniel Ruf <notifications@github.com> 於 2018年9月3日 週一 上午3:42寫道：

**Comment by DanielRuf** [comment]
I see no attached files:
https://github.com/amsul/pickadate.js/issues/1095

**Comment by Janny2018** [comment]
I have put code to https://codepen.io/janny2018/pen/MqpMjG
![screenshot](https://user-images.githubusercontent.com/42291583/44970988-88c6ab80-af86-11e8-8272-b72b678ff3c1.JPG)
[Code.txt](https://github.com/amsul/pickadate.js/files/2344444/Code.txt)



can you see that ? is that enough ? or something else more needed ? 
Thanks a lot

**Comment by DanielRuf** [comment]
It seems you copied the generated HTML code instead of the HTML source code (view-source:) and there are localhost references which prevent that it works here.

**Comment by DanielRuf** [comment]
The codepen does not load on my site so I can not test with this one.

**Comment by DanielRuf** [comment]
After some testing it loads but I see not the actual styles:
![bildschirmfoto 2018-09-03 um 09 02 43](https://user-images.githubusercontent.com/827205/44972071-2e165b00-af58-11e8-983c-885699c4fe7a.png)

**Comment by DanielRuf** [comment]
> So i removed that and now it's no longer scrolling back up but i have a different issue now where everytime i switch tabs the datepicker will automatically open.

I recommend opening a new issue for this.
I'll close this issue as resolved.

@Janny2018 please create a new issue with a working codepen as your issue is probably a different one.

**Comment by Janny2018** [comment]
ok , Thanks
