### ISSUE TITLE
 the dates reverse from right to left in the calendar

### ISSUE THREAD

**Issue by Janny2018** [amsul/pickadate.js#1099]
I posted this issue in #1095 comment, and Daniel suggested me to create a new issue,
so I  created a new issue(#1098), but after Submit that issue, it became closed, so I create the same issue here.

the screen shot is as below

![screenshot](https://user-images.githubusercontent.com/42291583/45006986-2d4ff880-b02e-11e8-8e9f-05ce45aebc65.JPG)

the code is part of an asp.net MVC project (semi-finished product), and
the project will access database,the View file(*.cshtml file) is in the attached files (item.zip)

I found though the screen shows the reversed result, but in the generated HTML code (after
screen show up I press F12 and copy whole element to save as a html
file, pls refer to the attached file --> generated.html.Code.txt) , the result will be correct.
and I also found something may cause this problem, but I don't know why ?
refer to the following ,

![f12 screen shot](https://user-images.githubusercontent.com/42291583/45007048-72742a80-b02e-11e8-9b7e-ad8de5aa4180.JPG)

why the value of the direction attribute is rtl ? does this mean right to left ?
and what in my code causes this ?

[item.zip](https://github.com/amsul/pickadate.js/files/2346968/item.zip)
[generated html Code.txt](https://github.com/amsul/pickadate.js/files/2346970/generated.html.Code.txt)

I don't know what happened, can someone help me to figure out the problem ? Thanks

**Comment by Janny2018** [comment]
I found it seems that the rtl.css causes this problem, and when I use code to set the CSS style for the picker class, everything  becomes normal. But I still don't know what in my code causes this case.

**Comment by DanielRuf** [comment]
Well, that is how `dir="rtl"` as setting should work.
