### ISSUE TITLE
got a "Cannot read property 'style' of null" error message

### ISSUE THREAD

**Issue by Janny2018** [amsul/pickadate.js#1100]
I use pickadate in my ASP.NET MVC project(a very simple project, only for test this tool),

and got a "Cannot read property 'style' of null" error message

the code rendered by ASP.NET is as the attached file :

[20180915-Q.txt](https://github.com/amsul/pickadate.js/files/2385532/20180915-Q.txt)

and my screen is as below (from a View file)
![20180915-4](https://user-images.githubusercontent.com/42291583/45584376-f2d73d00-b904-11e8-9b78-1b0ce14d718a.JPG)

when I click the date column, canlendar didn't show up
, so I press F12 to look up the code which is what I provided in the attached file, 
and can see there are some error messages  below

![20180915-q1](https://user-images.githubusercontent.com/42291583/45584284-611b0000-b903-11e8-861d-f36edc2e9e4e.JPG)

Is there anyone can help me to find out the solution ? Thanks

**Comment by DanielRuf** [comment]
Can you prepare a working codepen so we can reproduce it there?

**Comment by DanielRuf** [comment]
I can not do much with ASP.net as I have no experience with this platform. We need a recreated structure as pure HTML on codepen.

**Comment by Janny2018** [comment]
Thanks for your reply
I found that if I use Microsoft visual studio IDE tool Nuget to install the pickadate,
there will be the problem I mentioned, 
but if I download the zip file and put the code in the right directory
it works well
I think that is a problem caused by the IDE , so  I want to close this issue,
Before this I would like to thanks you for your concern about this issue.

**Comment by DanielRuf** [comment]
> I found that if I use Microsoft visual studio IDE tool Nuget to install the pickadate,
> there will be the problem I mentioned,
> but if I download the zip file and put the code in the right directory
> it works well

This is because the zip contains the latest changes which are not yet released.

**Comment by DanielRuf** [comment]
130 commits since the last release: https://github.com/amsul/pickadate.js/compare/3.5.6...master

**Comment by DanielRuf** [comment]
So nothing wrong with your IDE.
