### ISSUE TITLE
Disabling ranges in time picker

### ISSUE THREAD

**Issue by wasi007gh** [amsul/pickadate.js#1101]
Hey I am creating a booking plugin.

When a time is booked according to interval then that duration is disabled.

Like for example 3:00 PM to 4:00 PM ( interval 60 minutes )

when i set 

timepicker.set({

				disable: [
					{ from: new Date( '28 September, 2018 3:00 PM' ), to: new Date( '28 September, 2018 4:00 PM' ) },
				],
			});

Then 4 PM is also blocked but I don't want 4 PM to be blocked because that is the next slot and that has to be enabled

Even if I pass 3:59 PM the 4:00  slot is still blocked.

How to resovle this ?

**Comment by DanielRuf** [comment]
Hi, can you provide a codepen which demonstrates this issue?

Can you not block until max-1 (=3)?

**Comment by wasi007gh** [comment]
hey @DanielRuf Thankyou for max-1 concept, 

when passing endDateObj as (maxtime - currentBookingInterval)
It actually works perfectly.

:)
