### ISSUE TITLE
Change language filenames to en-US (UNICODE)

### ISSUE THREAD

**Issue by Yamakasi** [amsul/pickadate.js#1116]
Hi,

For standards it might be a good idea to change the locale filenames to dashed versions instead of underscore as browsers give it back dashed as well.

Also see: http://codel10n.com/what-is-correct-locale-tag-en_us-vs-en-us/

Keep up the good work!

**Comment by DanielRuf** [comment]
See https://github.com/amsul/pickadate.js/blob/master/lib/translations/NAMING.md regarding the current naming.

**Comment by Yamakasi** [comment]
> 
> 
> See https://github.com/amsul/pickadate.js/blob/master/lib/translations/NAMING.md regarding the current naming.

Yes but it uses the format of a standard without honoring the standard if you read it there, it's just a mix where the actual mix is a locale type of style tho.

**Comment by DanielRuf** [comment]
A PR is very welcome but we will not change it now as this would be a breaking change.

**Comment by Yamakasi** [comment]
> 
> 
> A PR is very welcome but we will not change it now as this would be a breaking change.

Yes I agree and can make a PR for it, but what would you like ? I think adding both versions is good to start with, it's seen with more libraries or maybe you have another suggestion ?

**Comment by DanielRuf** [comment]
Not both. We should only use one version and change the naming file and all references then.

**Comment by Yamakasi** [comment]
But isn't it a fact that you load the Language file yourself and not the library ?

**Comment by DanielRuf** [comment]
Yes, that's why I wrote that we should do this properly then. This includes docs, examples and so on. Still, everyone can rename the files like they want. So currently there is no real burden with the current naming.

If we change it (for example we load them using Node.js and bundle them in one project) it is a somehow breaking change which should not be part of a patch release.

**Comment by DanielRuf** [comment]
Makes not much sense as we would track 2 files and have to update 2 files per language. Minor / major update should bring this. A PR can be already provided.

**Comment by Yamakasi** [comment]
OK, let me dive into it!
