### ISSUE TITLE
wrong directions?

### ISSUE THREAD

**Issue by IIpepeII** [amsul/pickadate.js#1123]
Hi!

I think my problem is so special(or I'm special I really don't know @.@ ). So in my pickadate panel the Next Month button is at the left side, and the Previous Month button is at right side, and the days are in a strange direction as well. What happened? I didn't find anything about this in the documentation. 
![screenshot 20](https://user-images.githubusercontent.com/22872597/49810164-e4ac8780-fd60-11e8-8f3f-b1360073a6d9.png)

`dateConfig = {
    firstDay: 1,
    weekdaysShort: ['Mon', 'Tue', 'Wen', 'Thu', 'Fri', 'Sat', 'Sun'],
    showMonthsShort: true,
    clear: 'Clear',
    close: 'Cancel',
    today: '',
    formatSubmit: 'yyyy-mm-dd', //format for the server
    disable: [
        5,
        6,
        {
            from: [0, 0, 0], to: [
                new Date().getFullYear(),
                new Date().getMonth(),
                new Date().getDate()
            ]
        }
    ]
};`

Please help me!

**Comment by DanielRuf** [comment]
Hi @IIpepeII,

Did you set some rtl hint in your code?

**Comment by IIpepeII** [comment]
I don't think so! At first I accidentally linking the rtl.css but for while it is not part of the code. I deleted cache and make everything to forget about it, but my panel is still in wrong direction. :/

**Comment by IIpepeII** [comment]
Sorry for long waiting! So, I rebuilt the project from zero. And now it works I don't know how the rtl code remains in the old one. But now it works. So thy guys!

**Comment by DanielRuf** [comment]
Hi @IIpepeII, thanks for the update and letting us know, that it works now.
