### ISSUE TITLE
From and To  inputs working only in one form..

### ISSUE THREAD

**Issue by mafioznick** [amsul/pickadate.js#1124]
_Hi, I have some inputs for calendar working in one script:_

**1. Calendar** 
"From input"
 var datepicker = $('#date').pickadate({
...
"To input"
 var datepicker = $('#date2').pickadate({
...

**2. Calendar** 
"From input"
 var datepicker = $('#date3').pickadate({
...
"To input"
 var datepicker = $('#date4').pickadate({
...

_, but only in last one is working next script (When today is 12 day, I'm choosing  for exmpl From 17day, and To will be available from 17day..but only in calendar nr.2.. how to make that it will work in both?_

// Picker for 1 calendar // Choose date after chosen date script (only date)
var from_$input = $('#date').pickadate(),
    from_picker = from_$input.pickadate('picker')

var to_$input = $('#date2').pickadate(),
    to_picker = to_$input.pickadate('picker')

// Picker for 2 calendar // Choose date after chosen date script (only date)
var from_$input = $('#date3').pickadate(),
    from_picker = from_$input.pickadate('picker')

var to_$input = $('#date4').pickadate(),
    to_picker = to_$input.pickadate('picker')

// Check if there’s a “from” or “to” date to start with.
if ( from_picker.get('value') ) {
  to_picker.set('min', from_picker.get('select'))
}
if ( to_picker.get('value') ) {
  from_picker.set('max', to_picker.get('select'))
}

// When something is selected, update the “from” and “to” limits.
from_picker.on('set', function(event) {
  if ( event.select ) {
    to_picker.set('min', from_picker.get('select'))    
  }
  else if ( 'clear' in event ) {
    to_picker.set('min', false)
  }
})
to_picker.on('set', function(event) {
  if ( event.select ) {
    from_picker.set('max', to_picker.get('select'))
  }
  else if ( 'clear' in event ) {
    from_picker.set('max', false)
  }

})

**Comment by mafioznick** [comment]
any suggestions?

**Comment by DanielRuf** [comment]
@mafioznick did you find a solution?
