### ISSUE TITLE
iOS Keyboard

### ISSUE THREAD

**Issue by MatthewKennedy** [amsul/pickadate.js#1133]
When you click in the date field, as the date picker is opening the iOS keyboard appears and then disappears on the bottom of the screen, this plays havoc with body scroll lock.

**Comment by DanielRuf** [comment]
Hi, can you provide a codepen so we can reproduce this and provjde more info about the pickadate version that you use?

**Comment by DanielRuf** [comment]
Hi, can you provide a codepen so we can reproduce this and provide more info about the pickadate version that you use?

**Comment by MatthewKennedy** [comment]
Hi @DanielRuf 

I can't really as its an iOS only issue, but if you visit the https://amsul.ca/pickadate.js/date/ page in an iOS device click any of the date fields and look at the bottom of the screen you'll see the iOS keyboard appear then disappear.

**Comment by MatthewKennedy** [comment]
if you add onfocus="blur();" to the input field this prevents the flash of keyboard opening on iOS.

**Comment by MatthewKennedy** [comment]
`<input type="text" class="datepicker" onfocus="blur();" />`

**Comment by MatthewKennedy** [comment]
Instead of using the javascript to remove `readonly="readonly"` add `readonly="readonly" aria-readonly="true" onfocus="blur();"` to the target input element and no flash of keyboard on iOS, everything still works grand.
