### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by brendon** [amsul/pickadate.js#1136]
Hi @DanielRuf, per #1117, at your leisure, would you be able to make a new patch release? :)

**Comment by DanielRuf** [comment]
I think this is more than just a simple patch release, looks at least like a minor release.

See https://github.com/amsul/pickadate.js/compare/3.5.6...master

But we are currently working on v5 so it probably makes not much sense to create a new v3 release.

What do you think @amsul?

**Comment by brendon** [comment]
Lol, sorry, I didn't realise it'd been so long since the last release :D I guess if `v5` has the same base feature set (popup calendar), then it's all good to wait for it to be released. Otherwise, if it's quite a departure from the current codebase then perhaps a `3.6.0` release would be appropriate.

**Comment by DanielRuf** [comment]
Maybe we can prioritize the things or check the things that you are currently missing (if they are already in v5).

What do you currently miss in v3 (which exact patches, fixes, features)?

**Comment by brendon** [comment]
Thanks @DanielRuf, I'm currently just using the popup date picker as per: https://amsul.ca/pickadate.js/date/

plus the fix you merged for the modal overflow: https://github.com/amsul/pickadate.js/pull/1117

**Comment by DanielRuf** [comment]
Okay, I will check in the next days if this is also needed in v5 and I will provide this fix if this is the case.

If you need this now you can try `patch-package`. https://www.npmjs.com/package/patch-package

https://github.com/amsul/pickadate.js/pull/1117.patch or https://github.com/amsul/pickadate.js/pull/1117.diff provide can be also used with the native `patch` binary.

Let us know which solution you choose and if you need any help.

**Comment by brendon** [comment]
Thanks @DanielRuf, I never knew about `patch-package`! I think I'll stick with using yarn to bring in from the GitHub repo directly in the meantime:

"pickadate": "https://github.com/brendon/pickadate.js.git#e528acc02f1d9e638a99aa13c51b1fee35b012e2"

That's the commit where you merged my PR.

The upside of this approach is that I also get all the other improvements since the last release in 2015 (such as better Webpack support).

**Comment by amsul** [comment]
@DanielRuf I would imagine v5 is a while away from a stable release. Plus, it's got a different API and UI.

I can slice a new release for v3 so people don't have to point to specific commits. Do we feel master is stable at the current commit?

**Comment by DanielRuf** [comment]
`master` should be pretty stable. It contains only changes in translations and a few fixes and new unit tests.

I guess we have to update the changelog: https://github.com/amsul/pickadate.js/compare/3.5.6...master#files_bucket

**Comment by amsul** [comment]
@DanielRuf sounds good!

Tbh, I think we should stop using the Changelog markdown file in favor of notes on releases: https://github.com/amsul/pickadate.js/releases

So I'll ship a new version now and we can update the Release notes accordingly

**Comment by amsul** [comment]
And we're live! https://github.com/amsul/pickadate.js/releases/tag/3.6.0

**Comment by brendon** [comment]
Thanks @amsul and @DanielRuf :) Much appreciated.

For what it's worth, someone brought this to my attention the other day for an open source repo that I manage: https://keepachangelog.com/en/1.0.0/ Apparently it's still a good idea to keep a `CHANGELOG.md` changelog since Releases is locked away in Github and not readily discoverable by all (not everyone knows about the Releases section and it's not very obvious on the page). Just a thought :)

**Comment by DanielRuf** [comment]
> For what it's worth, someone brought this to my attention the other day for an open source repo that I manage: [keepachangelog.com/en/1.0.0](https://keepachangelog.com/en/1.0.0/) Apparently it's still a good idea to keep a `CHANGELOG.md` changelog since Releases is locked away in Github and not readily discoverable by all (not everyone knows about the Releases section and it's not very obvious on the page). Just a thought :)

Thanks for the input. This can be tedious sometimes. See https://github.com/DanielRuf/secure-shred/issues/9

But I understand how important changelogs are for users.

**Comment by DanielRuf** [comment]
https://github.com/amsul/pickadate.js/blob/master/CHANGELOG.md

**Comment by brendon** [comment]
Ha! Yes super tedious! We were using a generator: https://github.com/swanandp/acts_as_list/blob/master/CHANGELOG.md but the Added, Changed etc... headers are a big improvement and unfortunately it's not so easy to (though probably possible) to automate the categorisation of changes. I've just started the new style. The challenge will probably be remembering to update it! :)

**Comment by DanielRuf** [comment]
We would have to introduce commitlint then to reduce the overhead for us ;-)
We'll check what we can do to improve this for v5.

**Comment by amsul** [comment]
In my experience, given the dynamic nature of an open source project with commits coming in from anybody, it becomes an additional burden in merging PRs by tying commit messages to Release Notes.

If people still find it valuable to have a reference to finding a changelog within the repo code, I like the approach that [Vue](https://github.com/vuejs/vue#changelog) or [Redux](https://github.com/reduxjs/redux/blob/master/CHANGELOG.md) have taken of simply pointing to the Releases.

**Comment by brendon** [comment]
Good point @amsul :)
