### ISSUE TITLE
New release version breaking existing sites 

### ISSUE THREAD

**Issue by gautam-in** [amsul/pickadate.js#1137]
The latest version publised for pick a date i.e. 3.6.0 is breaking the existing site code which was running on 3.5.6. Will recommend publishing the new code as a major release instead of minor release as it breaks existing code.

**Comment by DanielRuf** [comment]
Hi, in general we recommend using lockfiles.

What exactly is not working anymore?

**Comment by holtkamp** [comment]
@gautam-in looking at the commit, only some CSS optimizations were done? What is breaking for you?

https://github.com/amsul/pickadate.js/commit/4f9e01d3df01f45f99f2229aa47b72d7471e2baa

@DanielRuf will the `3.6.0` release also "reach" [CDNJS](https://cdnjs.com/libraries/pickadate.js) automatically?

**Comment by DanielRuf** [comment]
> @gautam-in looking at the commit [4f9e01d](https://github.com/amsul/pickadate.js/commit/4f9e01d3df01f45f99f2229aa47b72d7471e2baa), only some CSS optimizations were done? What is breaking for you?

You have to check all commits between this tag and the previous tag / release ;-)

**Comment by DanielRuf** [comment]
https://github.com/amsul/pickadate.js/compare/3.5.2...3.6.0

**Comment by holtkamp** [comment]
Aah, yeah, was a bit to quick. Sorry

**Comment by DanielRuf** [comment]
@holtkamp regarding a CDNJS update, see https://github.com/cdnjs/cdnjs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

You can also use unpkg.
https://unpkg.com/pickadate/

In general I would not recommend the usage of CDNs as they can have and often had outages and there are privacy issues and other things (would not work without an internet connection).

**Comment by amsul** [comment]
As mentioned in https://github.com/amsul/pickadate.js/issues/1138#issuecomment-473473523, v3.6.1 should resolve this issue.
