### ISSUE TITLE
New update in chrome bugs the open method

### ISSUE THREAD

**Issue by FrederikSorensen** [amsul/pickadate.js#1143]
The new Chrome update (Version 73.0.3683.75) is making the css wierd on the open method, making it disappear right after open.

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/amsul/pickadate.js/issues/1138.

**Comment by DanielRuf** [comment]
Please update to the latest version and see the PR: https://github.com/amsul/pickadate.js/pull/1140
