### ISSUE TITLE
pickadate Auto Closing on Select

### ISSUE THREAD

**Issue by NicMacRoy** [amsul/pickadate.js#1146]
Having some weird functionality with this library that isn't consistent. I love the library and the clean display/functionality but recently I am having issues with it. 

As I select the input element to select a date, as soon as I focused the element the pickadate box appears then auto dismisses as if I lost focus on the element. Making it impossible to select a date as the box flickers within a split second.  I then figured it was possibly another event triggering causing me to lose focus but no other events are on this input.

After this if I switch Chrome browser tabs and go back to this page, the pickadate box appears and auto focuses me on the element.

Anybody else experience this or have any idea?

This is my instantiating of the pickadate element:

`		$('#txtFromDate').pickadate({
			formatSubmit: 'mm/dd/yyyy',
			hiddenName: true,
			selectYears: true,
			selectMonths: true
		});`

**Comment by DanielRuf** [comment]
Please try the latest release. Also see #1140

**Comment by DanielRuf** [comment]
Also see https://github.com/amsul/pickadate.js/issues/1138#issuecomment-473347446
