### ISSUE TITLE
Pickadate not working with materialize 0.100.2 with the latest chrome update

### ISSUE THREAD

**Issue by ArunAthisamy-03** [amsul/pickadate.js#1149]
Calendar window disappears immediately when the picker box is clicked. 

Ex : https://codepen.io/mcolynuck/pen/XeZzMJ?editors=1010
chrome v73.0.3683.86

**Comment by caseyjhol** [comment]
There are numerous issues discussing this problem, and it has been patched in the latest version. Please search next time.

**Comment by DanielRuf** [comment]
This is a Chrome regression bug and we have landed a small workaround for a few usecases in the latest release.

See #1138, https://github.com/amsul/pickadate.js/issues/1138#issuecomment-473347446 and https://github.com/amsul/pickadate.js/pull/1140

**Comment by riksnelders** [comment]
@ArunAthisamy-03 
Did u manage to fix this withing materialize ?

**Comment by zeeshanaligold** [comment]
@riksnelders

The solution is to filter the target with the parent: 
if ( target != ELEMENT && target != document && target != P.$root.parent()[0] && event.which != 3 )
