### ISSUE TITLE
Chrome bug, auto closes when opening

### ISSUE THREAD

**Issue by riksnelders** [amsul/pickadate.js#1153]
<script src="https://cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.6/picker.js"></script>

tested in IE 11, FF and chrome.
See recordit video => http://recordit.co/pGyReSeKRE
Auto closes on chrome, unable to pick date.

last one is chrome in the video. If alt tab and then alt tab back into chrome it shows up.

touch works fine, so does holding down left mouse button. It stays active then.

**Comment by DanielRuf** [comment]
Hi, please check the other issues. This should be "fixed" in the last 3.x release.

**Comment by DanielRuf** [comment]
In short: this is a regression bug in Chrome / Chromium.
