### ISSUE TITLE
Pickadate throws an error

### ISSUE THREAD

**Issue by laacz** [amsul/pickadate.js#1160]
When using only pickadate (without pickatime), translation lv_LV.js throws an exception, since it tries to extend non existant object object.

```
Uncaught (in promise) TypeError: Cannot read property 'defaults' of undefined at lv_LV.js?v=3.6.2:20
```

Here:

![image](https://user-images.githubusercontent.com/181486/56800800-8de1af00-6824-11e9-8d1f-661796575a7f.png)

Removing extend fixes problem.

**Comment by DanielRuf** [comment]
Hi @laacz,

all translation files have the same logic.

https://github.com/amsul/pickadate.js/blob/master/lib/translations/bs_BA.js

Also see https://github.com/amsul/pickadate.js/pull/1041#issuecomment-479599098 and https://github.com/amsul/pickadate.js/pull/744#issuecomment-479598406

**Comment by laacz** [comment]
@DanielRuf, but what if I do not require pikatime? Then there is no way to make this work witout mandatory import of pickatime?

**Comment by DanielRuf** [comment]
You can create a empty object using the following:

`jQuery.fn.pickatime = {defaults:{}}`

**Comment by laacz** [comment]
OK. Thanks. Is it not going to be fixed then? If so, then please close the issue :)

**Comment by DanielRuf** [comment]
Development focus is currently on v5 so v3 will not receive any big changes except critical things like the regression in Chrome 73.
