### ISSUE TITLE
Current date following up

### ISSUE THREAD

**Issue by bsgies** [amsul/pickadate.js#1164]
Hi,

If you notice that if today is 7th of May then the calendar will highlight today's date. But if you move to the next or previous month it keeps highlighting the 7th of every month too. How do I only highlight today's date and not every 7th?

**Comment by DanielRuf** [comment]
Hi @bsgies,

could you find a solution? If so please post the answer so others know it too.

**Comment by bsgies** [comment]
I ran into this issue as well. As a workaround, I remove the picker__day--highlighted class from every div with that class that doesn't have today's timestamp as data-pick value:

`var now = new Date();
var timestamp = new Date(now.getFullYear(), now.getMonth(), now.getDate()) / 1;

$('.datepicker').pickadate({
    onRender: function() {
        $('div.picker__day--highlighted').each(function(index, value) {
            if ($(this).data('pick') !== timestamp) {
                $(this).removeClass('picker__day--highlighted');
            }
        });
    }
});`
