### ISSUE TITLE
helm me 

### ISSUE THREAD

**Issue by antoariyanto** [amsul/pickadate.js#1165]
https://codepen.io/anon/pen/vwLXOz example ? how solution clik left problem

**Comment by DanielRuf** [comment]
Hi, please update to Pickadate 3.6.3.
https://codepen.io/DanielRuf/pen/ZNQLMG

This is a know issue with Chrome 73+, see https://bugs.chromium.org/p/chromium/issues/detail?id=941910 and the other closed issues like #1153.

**Comment by jairo-manalu** [comment]
> Hi, please update to Pickadate 3.6.3.
> https://codepen.io/DanielRuf/pen/ZNQLMG
> 
> This is a know issue with Chrome 73+, see https://bugs.chromium.org/p/chromium/issues/detail?id=941910 and the other closed issues like #1153.
We've just updated to 3.6.3 but still have the same problem. Is there anything else need to be done other than just updating. Thank you very much

**Comment by DanielRuf** [comment]
Hi @jairo-manalu,

Please open a new issue and provide a codepen and more relevant information.
