### ISSUE TITLE
[BUG] `editable: true` makes picker never closes

### ISSUE THREAD

**Issue by HeiVask** [amsul/pickadate.js#1170]
Tested on latest version (3.6.2) on Chrome 74.0.3729.157.

It can be seen at https://amsul.ca/pickadate.js/time/#editable.

To reproduce, just pick on "Try me" input. The picker opens but never closes.

Here's a demonstration:

![ezgif com-resize](https://user-images.githubusercontent.com/38522070/58250906-b3e66a80-7d62-11e9-8577-ea32cde6abd9.gif)

**Comment by DanielRuf** [comment]
Hi @HeiVask,

3.6.3 is the latest release. See https://github.com/amsul/pickadate.js/releases/tag/3.6.3

Can you try this too and provide a codepen so we can reproduce this?

**Comment by HeiVask** [comment]
Hi 👋 

I didn't notice about version. At https://amsul.ca/pickadate.js/ the download button still links to 3.6.2.

It seems the bug keeps there: https://codepen.io/heivask/pen/VOQMPX

**Comment by DanielRuf** [comment]
cc @amsul can you check the 3.6.3 release and link it on the website?
I remember there was a similar issue.

**Comment by DanielRuf** [comment]
https://github.com/amsul/pickadate.js/compare/3.6.3...master

We need a new patch release @amsul.
It works with the files from the current master branch.
https://codepen.io/DanielRuf/pen/VOQyzm

**Comment by amsul** [comment]
Just shipped 3.6.4 and also updated gh-pages. It should be fine now 👍
