### ISSUE TITLE
How to disable time after choose date in datetimepicker

### ISSUE THREAD

**Issue by rizki5411** [amsul/pickadate.js#1174]
I have two form, form date and form time.

```
$("#tanggal1").pickadate({
                min: true
            })


            $("#jam1").pickatime({
                min: [7,0],
                max: [15,0],
                interval: 60,
                disable: [
                    new Date(2019,7,2,13,0)
                ]
            }) 
```
How is it done so that when the user selects a date then the time will be disabled according to the date chosen. Thanks guys.

**Comment by DanielRuf** [comment]
Hi @rizki5411,

You can use the API for this.

https://amsul.ca/pickadate.js/api/
https://amsul.ca/pickadate.js/api/#method-set-disable-enable

Some example code:

```javascript
// get the timepicker instance

var $input = $('.datepicker').pickadate()

// Use the picker object directly.
var picker = $input.pickadate('picker')
picker.set('disable', [

  // Using a collection of arrays formatted as [YEAR,MONTH,DATE]
  [2016,9,3], [2016,9,9], [2016,9,20],

  // Using JavaScript Date objects
  new Date(2015,9,13), new Date(2015,9,24)
])
```

**Comment by rizki5411** [comment]
i see this example use pickadate, how to i use with **pickatime**?

**Comment by DanielRuf** [comment]
Try it with `.pickatime()`.

**Comment by rizki5411** [comment]
I'm trying to make a scheduling application. When the user enters a date (.pickadate) then from there the user enters the clock (.pickatime), now here he will check what time is busy from that date to then be disabled. How to do this mr?

**Comment by DanielRuf** [comment]
There are events and methods for hooking into the `change` and `submit` events.

**Comment by rizki5411** [comment]
Thank's mr, my problem has been clear

**Comment by DanielRuf** [comment]
For completeness the events: https://amsul.ca/pickadate.js/api/#events-callbacks
