### ISSUE TITLE
Prevent pickadate.js closing Bootstrap Dropdown menu form on spawn / click?

### ISSUE THREAD

**Issue by mahavinyasa** [amsul/pickadate.js#1178]

**Comment by DanielRuf** [comment]
Hi @mahavinyasa,

Please fill out the issue template.

Do you mean an issue that only occurs in Chrome 73+?

**Comment by DanielRuf** [comment]
Hi @mahavinyasa,

Please fill out the issue template and include a small reproducible testcase at codepen.

**Comment by mahavinyasa** [comment]
Issue seems completely fixed in 3.6.2 - Please ignore my ranting :)

**Comment by DanielRuf** [comment]
No problem and I do not see this as ranting =)

Any issue might be relevant.
