### ISSUE TITLE
Issue on disabling dates, overlapping months, wrong date being selected

### ISSUE THREAD

**Issue by MichaelBelgium** [amsul/pickadate.js#1179]
Using laravel 5.8 and having a `min` and `max` in pickadate options, it's selecting the wrong date.

I got this in javascript:

```
$('#date').pickadate({
    disable: [2],
    min: [2019,6,29],
    max: [2019,7,5]
});
```

It disabling every tuesday and you can max select a **week from now.** The dates are generated dynamicly (obviously). So if you would visit my page tomorrow it would say

```
$('#date').pickadate({
    disable: [2],
    min: [2019,6,30],
    max: [2019,7,6]
});
```

Going back to the first example, it results to this:

![image](https://user-images.githubusercontent.com/8951045/60337093-6503a480-99a2-11e9-8d9e-8645c2d84bd5.png)

First thing first: the month selected is _july_ wich is wrong (juli = dutch for july). Tomorrow, 29th is still june. Which then results in wrong date being selected, the date that get posted through is 2019/07/29, which should be 2019/06/29

```PHP
<input type="hidden" name="date_submit" value="2019/07/29">
```
 
Anyone encountered this before? I'm using version 3.6.3 from npm. Is this an issue due the localization or the core?

**Comment by DanielRuf** [comment]
Hi @MichaelBelgium,

your issue is about multiple single issues.
The month is 0-indexed so `6` is July.

**Comment by DanielRuf** [comment]
See the following note in the docs:

> NOTE: months in a JavaScript Date object are zero-indexed. Meaning, new Date(2016, 3, 20) is 20 April, 2016.

To stay consistent with this, whenever an integer is used in reference to a month, pickadate treats it as zero-indexed. Dates as strings are still parsed as expected.

https://amsul.ca/pickadate.js/date/

Can you also provide a small codepen which reproduces your issues?

**Comment by MichaelBelgium** [comment]
Ooh okay, that solves it. 

> your issue is about multiple single issues.

My intention was to only post about the wrong date being selected. But it all seemed so confusing to me at first

[Here's a pen](https://codepen.io/anon/pen/rEpyKp)

**Comment by DanielRuf** [comment]
So is your initial issue and question solved with this?

If this is the case, please close the issue
