### ISSUE TITLE
calendar won't open unless I call pickadata.open() four times

### ISSUE THREAD

**Issue by GreggGreen** [amsul/pickadate.js#1185]
This is the workaround I have to use:

```
while (picker.get('open') === false) {
	console.log('opening picker');
	picker.open();
}
```

**Comment by DanielRuf** [comment]
Hi @GreggGreen,

Please provide a codepen which reproduces your issue and provide some info about browser version and pickadate version.

**Comment by DanielRuf** [comment]
Closing as we did not get any codepen as reproducible testcase.
