### ISSUE TITLE
Possible Chrome bug again? Datepicker auto closes after focus is lost

### ISSUE THREAD

**Issue by purduekenny** [amsul/pickadate.js#1187]
Similar to issue #1138 

The date picker is showing similar signs that were displayed in issue #1138 from March. When clicking on a input field to display the date picker in Chrome it opens and closes immediately. It seems as if focus needs to persist in order for the date picker to stay open. Perhaps a Chrome update? 

We are using 3.6.0 after the previous Chrome bug cropped up.

**Comment by DanielRuf** [comment]
Hi @purduekenny,

there were 4 bugfix / patch releases, the latest should fix this.

https://github.com/amsul/pickadate.js/releases/tag/3.6.4

**Comment by purduekenny** [comment]
Daniel, thanks for the quick response! I JUST looked at the releases before posting and only saw 3.6.0, I'm sorry for wasting your time. We'll update our files and I'll report back if that doesn't work. Have a great day.
