### ISSUE TITLE
Disabled date off by 1 month

### ISSUE THREAD

**Issue by tsegreto** [amsul/pickadate.js#1188]
If you go to the example page, https://amsul.ca/pickadate.js/date/ it gives the example of

$('.datepicker').pickadate({
  disable: [
    [2015,3,3],
    [2015,3,12],
    [2015,3,20]
  ]
})

Yet if you click on the date picker it shows that April (the 4th month of the year) not March (the 3rd month of the year) date's are disabled. What's the deal with this?!?! I am having the same issue with my code, if I input [2019,8,19] it displays Sept 19th 2019 as disabled.

**Comment by DanielRuf** [comment]
Hi @tsegreto,

did you see the yellow notice on this page? Month is 0-indexed in JavaScript (0 = January, 11 = December).

**Comment by DanielRuf** [comment]
Closing as this is documented and excepted.
