### ISSUE TITLE
Change an option after picker initialization

### ISSUE THREAD

**Issue by ErnestBrandi** [amsul/pickadate.js#1192]
Hi, 
I can't find any solution to update an option value after the picker been initialized...
For instance I'd like to setup the `formatLabel` function on the fly depending on a user action.
Thanks 

EDIT : anyaway I found a way of doing my thing, here is the code

```
let time_start = $('#time_start').pickatime().pickatime('picker');
let time_end   = $('#time_end').pickatime({
	formatLabel: function(time) {
		// blabla
	}
}).pickatime('picker');

time_start.on('close', function() {
	time_end.trigger('formatLabel');
	time_end.render();
});
```

**Comment by woeterman94** [comment]
How did you solve this? 

For instance I want to change the option "selectyear" for some datepickers (after they have been initialized)
