### ISSUE TITLE
readonly attribute added to every input

### ISSUE THREAD

**Issue by djibe** [amsul/pickadate.js#1197]
Hi,
why does pickadate.js adds a readonly attribute to every input it is attached to ?
Could it be optionnal ?

It is breaking my styles.
Thanks for your help.

**Comment by DanielRuf** [comment]
Hi @djibe,

please see https://amsul.ca/pickadate.js/date/#editable in the documentation.

**Comment by djibe** [comment]
Oooops,
I feel stupid for asking what is in the doc.
Thanks
