### ISSUE TITLE
Disable date  on month is not correct

### ISSUE THREAD

**Issue by puwadon-book** [amsul/pickadate.js#1199]
Disable date month is +1 
Example I set disable date on 2019-12-1 but pickadate is show disable date on 2020-1-1 
i try to see in example code is same.

Sorry I'm not good at English

**Comment by DanielRuf** [comment]
Hi @puwadon-book,

This is how `Date` in JavaScript works, the month is zero-indexed.

See the note at the top of https://amsul.ca/pickadate.js/date/

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/povgKvN?editors=1111
