### ISSUE TITLE
Problem opening date picker in newer chrome on windows

### ISSUE THREAD

**Issue by p-psand** [amsul/pickadate.js#1200]
test url:
https://www.hibrighton.com/
with Chrome 79 on Windows (10&8)
Click the Check In or Check Out box within the Book Now section on the left of page.
The date picker opens and immediately shuts.
I have updated to version 3.6.2 on our stage server and still am having the same issues.
( https://psand:psand@www.holidayinn-kewgreen.cpep.co.uk/ )

i spotted issue https://github.com/amsul/pickadate.js/issues/1138
to be basically the same, and see that the new version has fixed the issue for me within Chrome 79 on Linux (my dev environment) but not for users on windows

i have stripped back all html, validation and jquery code related to the controls in a new page but to no effect on this behaviour:
https://psand:psand@www.holidayinn-kewgreen.cpep.co.uk/test-picker.html
This new page is following the base setup for a date picker control only

i have run out of wild geese to follow now, sorry.

**Comment by DanielRuf** [comment]
Please try pickadate 3.6.4

https://github.com/amsul/pickadate.js/releases/tag/3.6.4

**Comment by p-psand** [comment]
sorted! many thanks
