### ISSUE TITLE
How to make already open Date-Picker in a modal ?

### ISSUE THREAD

**Issue by Avtarsodhi** [amsul/pickadate.js#1201]
![modal-picker](https://user-images.githubusercontent.com/44052289/73590609-6550b900-450a-11ea-83df-441b355f0691.PNG)

 Hey,

I am opening a modal on click the input field and i want the date-picker as an already open Calendar with an hidden input field. I have already tried autofocus on hidden input and trigger click event on input field but it is not going as per my expectations. 

Please help me and give my some suggestions to resolve it.

Thanks in advance.

**Comment by DanielRuf** [comment]
Hi @Avtarsodhi,

Please provide a codepen so we have a working reproducible testcase.

**Comment by Avtarsodhi** [comment]
Hi @DanielRuf My jsp's code is 
<input onclick="openDatePickerModal()" placeholder="Delivery Date">

and javascript code is-
function openDatePickerModal() {
   $('.picker-modal').openModal();
}'

and pickadate code is-
$('#deliveryDatePicker' .pickadate({
                formatSubmit: 'dd/mm/yyyy',
            })

modal code is - 
<div class="modal-content" style="height: 85%">
           <input type="date" placeholder="Delivery Date" id="deliveryDatePicker">
</div>

**Comment by DanielRuf** [comment]
This is not a codepen. Please go to codepen.io and create a working example of your current implementation (only css, js, html).

**Comment by DanielRuf** [comment]
Did you already try the `open` method?

https://amsul.ca/pickadate.js/api/#method-open-close

**Comment by Avtarsodhi** [comment]
![picker-error](https://user-images.githubusercontent.com/44052289/73632057-b84c7c80-4680-11ea-9e0d-a1fb02e5e438.PNG)

how to use pickadate.js in code-pen. it shows the error.

**Comment by Avtarsodhi** [comment]
@DanielRuf 

yeah, i have tried open function but it shows error picker is not defined

**Comment by DanielRuf** [comment]
Please check the docs at the top:

```
var $input = $('.datepicker').pickadate()

// Use the picker object directly.
var picker = $input.pickadate('picker')
picker.methodName(argument1, argument2, ...)
```

What exactly did you try on codepen?

**Comment by DanielRuf** [comment]
Keepn in mind that you have to import / load the datepicker and picker file.

https://github.com/amsul/pickadate.js/tree/master/lib

**Comment by DanielRuf** [comment]
You have to load picker.js before loading the date.picker.js file:

https://github.com/amsul/pickadate.js/tree/master/lib

**Comment by Avtarsodhi** [comment]
Thanks @DanielRuf for your quick response. 

It works.
