### ISSUE TITLE
Webpack and pickadate still not working

### ISSUE THREAD

**Issue by iammichiel** [amsul/pickadate.js#1212]
Hi there, 

I am trying to integrate pickadate in a modern front-end workflow. We are using Webpack and I would like to add this part of the app to that workflow. Everything compiles fine but at runtime, I have : `$(...).pickadate is not a function` error. 

I have tried about everything discussed here and there online :
- Adding a new rule 
- Disabling the import for the loader, 
- Autoprividing jQuery, 
- Changing the factory code.

Related issues :  #870 , #775 , #772 #779

So far nothing works.

**Comment by DanielRuf** [comment]
> $(...).pickadate

You have to install jQuery (as devDependency), import / require it and bundle it using the `externals` config from webpack.

https://webpack.js.org/configuration/externals/

**Comment by DanielRuf** [comment]
Also please provide a reproducible testcase (as repository) so we can check that if `externals` does not solve your issue.

**Comment by jirsbek** [comment]
I can confirm. Using externals option in `webpack.config.js` works well.

```
module.exports = {
  //...
  externals: {
    jquery: 'jQuery'
  }
};
```

**Comment by DanielRuf** [comment]
Closing as this should be resolved with the correct webpack setup and configuration.
