### ISSUE TITLE
RequireJS and Legacy.js support

### ISSUE THREAD

**Issue by halcyonandon** [amsul/pickadate.js#136]
I wasn't able to find a definitive answer to this question, but I'm using pickadate with requirejs and backbone. What would be the best way to integrate legacy.js with requirejs for older browser support.

Simply including both pickadate and legacy in requirejs.config does not work. 

thanks

**Comment by Aure77** [comment]
Actually loading translation with requirejs cause : `TypeError: jQuery.fn.pickadate is undefined`
What's about using requirejs for translations ?
