### ISSUE TITLE
The best way to get the calendar object itself?

### ISSUE THREAD

**Issue by amster** [amsul/pickadate.js#15]
I'm trying to remote control the calendar widget. I peered into the code and it seemed the way to get the calendar object was to do:

```
cal = $('SELECT THE TEXT FIELD').data("widgets.datepicker").calendar;
```

Then I can:

```
cal.close();
cal.open();
```

Is this the best way? Or are these meant to be internal methods only?

**Comment by serevok** [comment]
The link is broken =(
