### ISSUE TITLE
Correct way to set date value from JS ?

### ISSUE THREAD

**Issue by softshape** [amsul/pickadate.js#166]
If I need to update date value from JavaScript, what is the correct way to do this? So far I've tried -

```
$('#date').data('value', new_date);
$('#date').pickadate().pickadate('picker').render();
```

with no much success.

**Comment by Lexxtor** [comment]
It's still not working.
I found one strange way to set date:
```js
$('#demo__api-open-close').pickadate('set').set('select', new Date(2015, 3, 30));
```
And this samples don't work:
```js
$('#demo__api-open-close').pickadate().set('select', new Date(2015, 3, 30));
$('#demo__api-open-close').pickadate('set', 'select', new Date(2015, 3, 30));
```
But the second should work, as it described in docs.

**Comment by andrewmartin** [comment]
@Lexxtor thanks so much for posting that working solution. Was going crazy trying to figure this one out.

:+1: to update the docs with more clarity here...

**Comment by amsul** [comment]
@andrewmartin the easiest way to interact with it is to get the picker:

```js
var picker = $('#demo__api-open-close').pickadate('picker')
picker.set('select', new Date(2015, 3, 30))
```

Hope that clarifies things.

**Comment by andrewmartin** [comment]
Is it possible to have a null (empty) value on initialize? I'm having some issues with validation. 



—
Andrew Martinandrewmart.in

**Comment by fiatux** [comment]
+1 on @Lexxtor

**Comment by brendanfalkowski** [comment]
For anyone who got stuck on this:

``` javascript
var picker = $('#demo__api-open-close').pickadate('picker')
picker.set('select', new Date(2015, 3, 30));
```

You might be too smart assuming the string `pickadate('picker')` was the variable name. This example would be clearer:

``` javascript
var myPicker = $('#demo__api-open-close').pickadate('picker')
myPicker.set('select', new Date(2015, 3, 30));
```
