### ISSUE TITLE
Complete date reset

### ISSUE THREAD

**Issue by foodgy** [amsul/pickadate.js#171]
Is it possible to reset calendar date completely?

I mean <b>remove input value</b> and <b>reset year, month, day</b> to current date.
Reset calendar to its initial state.

**Comment by Vishwaas** [comment]
@amsul  does picker.stop().start() does not start the picker it only stops it

**Comment by nxtpl** [comment]
Found a way to "reset" the calendar date to the current day:
$(".picker__input").pickadate().pickadate("picker").set("view", new Date());

Someone could add a .reset() method to this library ;)

**Comment by DanielRuf** [comment]
> Someone could add a .reset() method to this library ;)

If it is not yet implemented, PRs are very welcome =)

**Comment by nxtpl** [comment]
Called it .today() and submitted the PR :)
https://github.com/amsul/pickadate.js/pull/1090
