### ISSUE TITLE
Brazil timezone: Two dates repeating on october month.

### ISSUE THREAD

**Issue by rdenadai** [amsul/pickadate.js#180]
Hi there!
Found a little bug on the pickadate widget... don't know if this is a specific bug, because i'm from Brazil. Anyway, i attach a image showing the bug...
The october month shows two 19 days... it doesn't matter the year i choose, the same thing occours to other days in october.

![pickadata](https://f.cloud.github.com/assets/917516/826376/01b9399e-f084-11e2-9150-5879d422ef5a.png)

Thanks

**Comment by albertjose** [comment]
This problem was solved? For me the problem is repeated in all October months (using Firefox Browser).
