### ISSUE TITLE
Wrap files in UMD modules (including translations)

### ISSUE THREAD

**Issue by joefiorini** [amsul/pickadate.js#210]
It would be much easier to use this with requirejs/browserify if we wrapped the 3 picker files (picker.js, picker.date.js and picker.time.js) in UMD modules (see http://github.com/umdjs/umd). I am going to try to implement this using the `grunt-umd` plugin for my own use, would you be willing to accept a PR with such a feature?

**Comment by mightydes** [comment]
What about translations?)

**Comment by peschee** [comment]
> What about translations?

Any updates on this?

**Comment by amsul** [comment]
Opening this until that’s done

**Comment by DanielRuf** [comment]
We should handle this with webpack then.
