### ISSUE TITLE
Can I show the widget only after click on other element?

### ISSUE THREAD

**Issue by diegoviola1** [amsul/pickadate.js#219]
Hello.

I created a button with a calendar icon and I want to show the widget only when the user click on it. On the calendar button I have an "data-input" with the value of the input id where I have to display the widget.

```
<input type="text" class="dateFormat" id="test1">
<div class="calendar-container" data-input="test1">
```

There is a way to show pickadate on test1 input without click on it?

**Comment by TkNeo** [comment]
I wan the date picker to only show the calendar portion. I dont care about the header showing the weekday and the big day, date and year. I only care about the calendar part as shown here [http://imgur.com/NfT6W95](url). Can anyone help me figure out what settings allows this ? I looked into the documentation by amsul but could not figure it out.
