### ISSUE TITLE
expected Hash (got String) for param `date'

### ISSUE THREAD

**Issue by DevanB** [amsul/pickadate.js#227]
When using pickadate in Rails, I get the following error when submitting a form:

expected Hash (got String) for param `date'

Here is my form and schema for the two fields: https://gist.github.com/DevanB/6551291

I can remove pickadate classes from the fields, and everything works fine, but when those two fields have the pickadate classes, I get that error.

Thanks for any help guys!

**Comment by acrolink** [comment]
@jerefrer Thank you very much. You suggestion works perfectly.
