### ISSUE TITLE
From & to calendars 

### ISSUE THREAD

**Issue by oozrafa** [amsul/pickadate.js#233]
Hey. I can't seem to find an example as to how to do this with the new v3 api. Could you please advise?

Here is how it's done with the jquery ui datepicker:

``` javascript
 $( "#from" ).datepicker({
onClose: function( selectedDate ) {
$( "#to" ).datepicker( "option", "minDate", selectedDate );
}
});

$( "#to" ).datepicker({
onClose: function( selectedDate ) {
$( "#from" ).datepicker( "option", "maxDate", selectedDate );
}
});
```

**Comment by rafaelbuiu** [comment]
I am getting an error using this:

Uncaught RangeError: Maximum call stack size exceeded

**Comment by akash-suthar** [comment]
$('.datepicker').on('change', function () {
                    if ($(this).attr('id') === 'datefrom') {
                        alert($(this).val())
                        $('#dateto').pickadate('picker').set('min',$(this).val());
                    }
                    if ($(this).attr('id') === 'dateto') {
                        $('#datefrom').pickadate('picker').set('max',$(this).val());
                    }
                });

**Comment by dbr0** [comment]
An upgrade from what @akash-suthar did:

```
$('.datepicker').on('change', function () {
    if ($(this).data('datepicker_from_or_to') === 'from') {
        $('#'+$(this).data('datepicker_to_target')).pickadate('picker').set('min',$(this).val());
    }
    if ($(this).data('datepicker_from_or_to') === 'to') {
        $('#'+$(this).data('datepicker_from_target')).pickadate('picker').set('max',$(this).val());
    }
});
```
and in the veiw

```
<input type="date"
                       class="datepicker"
                       id="new_term_start_date"
                       data-datepicker_from_or_to="from"
                       data-datepicker_to_target="new_term_end_date"
                >
```

and

```
<input type="date"
                       class="datepicker"
                       id="new_term_end_date"
                       data-datepicker_from_or_to="to"
                       data-datepicker_from_target="new_term_start_date"
                >
```

**Comment by elirant3** [comment]
> The best way to do this is linked on the [homepage](http://amsul.ca/pickadate.js/#features), http://codepen.io/amsul/pen/nGckA
> 
> ```js
> // Check if there’s a “from” or “to” date to start with.
> if ( from_picker.get('value') ) {
>   to_picker.set('min', from_picker.get('select'))
> }
> if ( to_picker.get('value') ) {
>   from_picker.set('max', to_picker.get('select'))
> }
> 
> // When something is selected, update the “from” and “to” limits.
> from_picker.on('set', function(event) {
>   if ( event.select ) {
>     to_picker.set('min', from_picker.get('select'))
>   }
> })
> to_picker.on('set', function(event) {
>   if ( event.select ) {
>     from_picker.set('max', to_picker.get('select'))
>   }
> })
> ```
> 
> I feel the `close` event is a tad too late and you wanna update it on `set`. Cheers!

Thanks
