### ISSUE TITLE
Safari iOS 7.0 crashes with dropdown selectors

### ISSUE THREAD

**Issue by l-i-n-k** [amsul/pickadate.js#237]
My mobile safari crashes when trying to use the dropdown selectors (month/year) on your demo page.

iOS 7.0 German
http://amsul.ca/pickadate.js/date.htm#selectors

**Comment by pedrodelgallego** [comment]
Same issue here, when I click on month/year and select a different year the browser crash 

I am using the example at http://amsul.ca/pickadate.js/date/ 
iOS 7

@l-i-n-k  were you able to find a fix for this?

**Comment by reenumathew** [comment]
I am also getting this issue. Any solution for this?
