### ISSUE TITLE
Need to get picker to always be open? - previous answer now 404 :(

### ISSUE THREAD

**Issue by chriswible** [amsul/pickadate.js#241]
I absolutely love this picker. I actually just want to display the picker and not have it toggle visibility at all. I found a previous request for this but the link that references an answer is broken. The response hinted that the solution has something to do with styling. I took a look at the css, and I'm getting the feeling that this may no longer be true in v3.

This is so well written that I'm guessing the solution is simple and I'm just not seeing it.

I did pass in false to open() - however, that still closed after interaction. Additionally, when I clicked on the input, it appeared to open another instance of the calendar.

My end goal: hide the input that the calendar binds to and simply show a calendar instead of the input.

**Comment by hobberwickey** [comment]
I know this is old, but the easiest answer I've found is just to add the opened class as the standard class like

```
$(el).pickadate({
  klass: {
    picker: "picker picker--opened"
  }
})
```

This will make the picker appear in it's opened state all the time.

**Comment by chriswible** [comment]
@hobberwickey  - nicely done. If that works, it's far more forward compatible than my css hacking.

**Comment by hobberwickey** [comment]
@chriswible Was so close, edited my answer. Forgot to replace the opened class with something else so that "picker--opened" doesn't get remove when a date is selected.
