### ISSUE TITLE
opening pickadate from a modal in Bootstrap v3

### ISSUE THREAD

**Issue by sithwarrior** [amsul/pickadate.js#243]
Using pickadate on an input field in a modal, results in not beeing able to pick a date.

Tested by openeing a modal with a regular input field
<input id="contractPauseStart" type="text" class="form-control" placeholder="Text input">

enhanced by 
$('#contractPauseStart').pickadate();

expected:
To be able to pick a date

result:
Chrome: picking a date fails if an input field or something similar is underneath the picker, in the modal. The datepicker closes.
Safari: Rendering of the datepicker i garbled. See screenshot
![screen shot 2013-10-07 at 7 23 21 pm](https://f.cloud.github.com/assets/1550819/1282522/57a0a952-2f75-11e3-8fb6-978f956b5aba.png)

**Comment by zinwalin** [comment]
@mariofischer awesome workaround, thanks a lot.
