### ISSUE TITLE
Displaying dates in different colours

### ISSUE THREAD

**Issue by jasonrunghen** [amsul/pickadate.js#259]
Is it possible to have the infocus dates in different colours.... ie one array of dates displayed in one colour and another array of dates in another color....

purpose of this is green days people can make as many bookings as they like, but on amber days we have limited spaces. 

many thanks

**Comment by adinugro88** [comment]
hey when i click next why color is missing??

**Comment by adinugro88** [comment]
when i click next or prev month why the color is missing ???

how can i put list holiday under the date by following month ??
