### ISSUE TITLE
Month Dropdown Selection Does Not Work On Samsung Galaxy Note, S3 & S4 default Android Browser

### ISSUE THREAD

**Issue by YodasMyDad** [amsul/pickadate.js#262]
Found a bit of a show stopper today using v3.3.0 :( 

We are using your picker with the year and month dropdowns to let users select their date of birth.

Unfortunately users are unable to select a year or month on the default Android web browser, they can click the dropdowns the default Android UI appears and you can scroll through the years or months. If you select one, and then click done the default UI box closes but the datepicker is not updated - Making it unusable for a responsive site.

This has been tested on both a Galaxy S3 & Galaxy S4 using the default web browser you get with the phone.

Any pointers on how to get this working with Android ASAP would be great. Or we'll have  to resort to using something else, something I don't really want to do as I love how your picker works/looks.

**Comment by jessek1** [comment]
I'm having the same issue on a Galaxy Alpha.  It would seem we should try and debug this issue if Samsung is ~65% of global market share of Androids.
