### ISSUE TITLE
Pickadate's formatSubmit option not changing original input's format

### ISSUE THREAD

**Issue by keithmuth** [amsul/pickadate.js#295]
It's my understanding that pickadate creates a hidden input with the name of the visible form input you applied it to plus &quot;_submit&quot; (e.g. name=&quot;date&#95;submit&quot;), I can chose the formatting for the hidden field as well as the visible field's formatting (I need the format submit format a certain way to pass validation), and then pickadate will swap out and post the original input using the format I specified in the formatSubmit option. I'm calling pickadate like so:

```
$("#date").pickadate({
    format: 'mmmm d yyyy',
    formatSubmit: 'yyyy-mm-dd'
});
```

Using those options, I'm seeing both the hidden field and visible field get their respective formats from pickadate, however when I submit the form I'm seeing both fields ("date" and "date_submit") coming through in the post with their formats I set above. In other words, "date" is being posted using the "format" option, not "formatSubmit" like I need it to. This is causing validation to fail.

The only way I've found to fix the problem is to remove the suffix in the name of the hidden field to match the visible field's name, but that feels wrong. This is what I'm doing to make it pass validation:

```
$("#date").pickadate({
    format: 'mmmm d yyyy',
    formatSubmit: 'yyyy-mm-dd',
    hiddenSuffix: ''
});
```

Is this the way I should be doing it, is it a bug, or am I missing something? I'm using version 3.3.1 of pickadate.

**Comment by NicolasCharpentier** [comment]
Hidden fields doesn't replace the seen field in GET submission.

Working with pickadate.js from materialize ( http://materializecss.com/forms.html )

I get this `http://localhost:81/stats?minDate=13+Octobre+2016&minDate=2016-10-13&maxDate=04+Octobre+2016&maxDate=2016-10-04`

**Comment by lnpbk** [comment]
A little late to the party, but @NicolasCharpentier if you're still having your issue, the solution is to add `hiddenName: true`, as per the docs (http://amsul.ca/pickadate.js/date/#formats_use_hidden_only)

**Comment by luqmanrom** [comment]
@lnpbk Thanks! It works for me
