### ISSUE TITLE
plugin ignores HTML5 validation related attributes

### ISSUE THREAD

**Issue by chrisdlangton** [amsul/pickadate.js#301]
All inputs activated with this plugin are essentially replaced with a hidden input and none of the HTML5 validation related attributes are honoured.

example using attributes;

```
required="required"
pattern="^[0-9+]*$"
```

`required` is most important, but `pattern` is to enforce format (I used `Ymd` for this example so my `pattern` expects only numeric values) and give instant feedback to the user.

Once activated the resulting input did not validate on submit.

Minimum expected outcome, the plugin adds an event listener to the form submit event and checks its instances for inputs with;
1) `required` to ensure they have a value
2) `pattern` to ensure the value passes the supplied regex
3) on failure of either test a message (based on `title` attribute) is displayed under the instance input.

There are many other HTML5 form attributes that could impact this plugin.

**Comment by clarkgriswold** [comment]
@amsul I'm a bit confused about this. Setting editable to true effectively disables pickadate altogether [https://github.com/amsul/pickadate.js/blob/master/lib/picker.js#L631](https://github.com/amsul/pickadate.js/blob/master/lib/picker.js#L631). Once you do this there is no way to open the pickadate modal as focus, click and keydown events are no longer reachable. This is the case on your demo page as well [http://amsul.ca/pickadate.js/date/#editable](http://amsul.ca/pickadate.js/date/#editable). 

So we initialize pickadate with a setting that disables pickadate... Am I missing something? That seems bassackwards to me. 

Removing that condition gives me exactly what I want; an element that responds to HTML5 input validation, yet still works with pickadate. 

Would it not make more sense to get rid of the editable config setting and that condition on line 631 in favour of a readOnly config setting to allow users to set the field to readOnly if that's what they really want? In the case where people don't want to use readOnly force the use of pattern with a note that devs should also be validating that pattern server side?

I feel like pickadate should still work with and without readOnly, but perhaps there is a good reason for this.

Thanks for your time.
