### ISSUE TITLE
'onSet' event triggering when changing month or year from select lists ?

### ISSUE THREAD

**Issue by gostbuster** [amsul/pickadate.js#309]
Hi,

I enabled the selectYears and selectMonths options and I noticed that when I was changing month or year from the select lists, the "onSet" event was triggered ?

Is it normal ?

Thanks,
Regards

**Comment by VamosErik88** [comment]
If someone wants to prevent onSet event form firing, just check if the input value is null or empty.

    onSet: function() {
	    var s = picker.get("select", "yyyy/mm/dd");
        if (s == null || s=="") {
			//do nothing
        } else {
            //do what you want to do
        }
Hope this helps ;)

**Comment by isaachinman** [comment]
@VamosErik88 Presumably this only works on the first initiation, if someone re-opens the picker to choose a new date, the problem persists.
