### ISSUE TITLE
Disable future dates

### ISSUE THREAD

**Issue by chintanbanugaria** [amsul/pickadate.js#321]
Hi,
Is there any way to disable all the future dates apart from today and past ? for e.g. if today is 15th January 2014, then all the dates from 16th January 2014 should be disabled.

Thanks for your help.
Chintan

P.S. Awesome work mate.

**Comment by ScreamZ** [comment]
Is there a way to set max to unlimited, or I should set to an big number that people won't reach ? (like 20000) ?

**Comment by mannoeu** [comment]
> @amsul You just use `max: new Date()` to disable all future dates.

it works? the time will come differently I believe, so 02-10-2020T12:40:33 != 02-10-2020T12:40:34, i used max(new Date()) and paste new Date() on my picker and not works.
