### ISSUE TITLE
Embed pickadate in open state inline in html document

### ISSUE THREAD

**Issue by malthoff** [amsul/pickadate.js#331]
Is there a way to embed pickadate in the page directly - without the need for an visible input field? I tried to do that but it seems like it's not meant to used that way.
I want to have it rendered into the page on page load and keep it open, even after the user has chosen a date - more like a calendar widget.

**Comment by cl4rke** [comment]
@amsul this is a different issue. #323 is opening the calendar for non-input tags. This issue is for having pickadate as a widget, not a popup. +1 for this.

**Comment by ZweisteinT** [comment]
Any News on this? Is it able to be rendered on a html site without any selectsboxes?

**Comment by DanielRuf** [comment]
> without the need for an visible input field

The form input saves the value for forms where calendars are normally used. I don't think that we would change this.

> Any News on this? Is it able to be rendered on a html site without any selectsboxes?

I guess you mean `input[type="text"]`

**Comment by DanielRuf** [comment]
> without the need for an visible input field

The form input saves the value for forms where calendars are normally used. I don't think that we would change this.

> Any News on this? Is it able to be rendered on a html site without any selectsboxes?

I guess you mean `input[type="text"]`.
