### ISSUE TITLE
Multiple calendar months on one instance.

### ISSUE THREAD

**Issue by dkarigithu** [amsul/pickadate.js#379]
I would like to setup a datepicker that has multiple calendars in the same view i.e.

August       |         September

Does pickadate currently support such a setup? Been thinking about using the render method however wiring that up back to pickadate will be challenge.

**Comment by xtianus79** [comment]
I need this functionality too.  Is this possible?

**Comment by xtianus79** [comment]
I want to use it for the class css too.  I need it to be displayed for a booking widget.
