### ISSUE TITLE
Allow year selector to be moved before month.

### ISSUE THREAD

**Issue by a-am** [amsul/pickadate.js#384]
We keep running into issues with users where the ui is confusing.  When we have "max:true"  and some of the months are greyed out it is confusing to the user having to change the year first to select the month.  But if we remove max:true then we have years  we don't need in the picker.  So if the year select could be moved before the month that would help usability.  Or the ability to toggle that.

**Comment by LiuQiTangli** [comment]
I have a problem: the font-size of year and month is too large to display completely. please skin my picture and someone give me a solution. Thanks!
![dd0f tmp](https://cloud.githubusercontent.com/assets/23690752/20549938/a4ff0010-b16b-11e6-8a38-eaa4b66b746b.jpg)

**Comment by serg33v** [comment]
@LiuQiTangli  just remove padding from select elements: 
```
.picker__select--month, .picker__select--year {
	padding:0;
}
```

**Comment by gregblass** [comment]
How would one go about restoring this to how it worked before - that is, display the month before the year?
