### ISSUE TITLE
Disable for Browsers with Date Support

### ISSUE THREAD

**Issue by benbjohnson** [amsul/pickadate.js#4]
It would be nice to only show pickadate.js for browsers that don't have built-in `type="date"` support. It looks good on my browser but it's more difficult to use on my iPhone because of the screen real estate and lack of automatic scrolling.

**Comment by paambaati** [comment]
@amsul The link (http://amsul.github.com/pickadate.js/docs.htm#disable) is broken, and I can't find this on the API page (http://amsul.ca/pickadate.js/api/) either. Can you help find the docs for this option?
