### ISSUE TITLE
Calendar won't close on date select

### ISSUE THREAD

**Issue by TheSisb** [amsul/pickadate.js#40]
As per the docs, I'm doing:

$('.datepicker').pickadate({
      onSelect: function() {
            this.close();
      }
});

and the calendar does not close.  I'm not sure but I think the calendar is closing and reopening every time a date is selected (why is that anyways?), and that action is taking precedence over mine.

How do I get it to close on select?

**Comment by victorkurauchi** [comment]
@TheSisb tkz, i was facing the same problem
