### ISSUE TITLE
Month Picker only

### ISSUE THREAD

**Issue by mehargags** [amsul/pickadate.js#425]
Hi Amsul
Love your plugin. was wondering if the datepicker can only be used for month/year only-- specifially speaking I want a month picker only. This is needed for Credit Card expiry fields and similar categories where a DAY is NOT required.

please do let me know.. keep up the good work

--Gagan

**Comment by hungchip** [comment]
Have you  realeseed v4 yet? I realy need  pick month and year only feature for credit card
