### ISSUE TITLE
picker.on({ set: function }) is called when you navigate to next month

### ISSUE THREAD

**Issue by arubacao** [amsul/pickadate.js#445]
I noticed that "set" is fired when you navigate to the next (or previous) month.
I don't know if you did that on purpose, but maybe it is better if it is just fired when a real date is picked.

Example:

This Code:
datepicker.on({
    set: function() {
       console.logdatepicker.get('select').obj.getTimezoneOffset());
    }
});

if i navigate to the next month without selecting a date previously, it gives me this error messeage:

Uncaught TypeError: Cannot read property 'obj' of null

(of course, because there is no obj)

Best regards,
arubacao

**Comment by xoco70** [comment]
Hi, 

I have the same error, but could not fix it with indications above.... Can you help me?

It seems it works when I first select a date, and then change month, but when I change month first I get the same mistake...

I tried:                 

`muted: true
`
or 
```
pickerIni.on({
render: function() {
                    console.log('Just rendered anew')
                },
});

```
But it doesn't work, stilll can't change months
