### ISSUE TITLE
Trigger not working?

### ISSUE THREAD

**Issue by rohan-deshpande** [amsul/pickadate.js#448]
I'm trying to open pickers from different selectors in the DOM, but I can't get it to work using the trigger method (which I think should be the correct way to do it). 

In your example http://amsul.ca/pickadate.js/api.htm#method-trigger If I hit the Trigger open callback button, the string gets logged in the console, but the picker does not open.  Should it not open when the open event is triggered?

I'm testing in Chrome on the mac and here's my code

``` javascript
pickadateContainer:function(target , container , activators)
{
    var scope = this;

    if($(scope.defaults.booked_selector).length)
    {
        scope.defaults.disable = $(scope.defaults.booked_selector).data('booked');
    }

    var picker  =   $(target).pickadate(
                    {
                        container:container,
                        format:'dd/mm/yyyy',
                        formatSubmit: 'yyyy-mm-dd',
                        disable:scope.defaults.disable,
                        weekdaysShort:['S', 'M', 'T', 'W', 'T', 'F', 'S']
                    });

    picker.on('open' , function(){console.log('picker has opened');}); //edit

    $.each(activators , function(index , item)
    {
        $(item).on('click' , function(e)
        {
            e.preventDefault();
            picker.trigger('open');
        });
    });
}
```

Edit: have added a log to test the open event, it logs correctly but the picker doesn't open.

**Comment by dfusionTownsend** [comment]
e.stopPropagation(); 

Fixed the issue for me too.
