### ISSUE TITLE
Timepicker doesn't scroll in IE 8

### ISSUE THREAD

**Issue by NateWr** [amsul/pickadate.js#467]
The timepicker doesn't respond to mouse scrolling when testing with XP and IE8 using the [VMs that Microsoft provides](https://www.modern.ie/en-gb/virtualization-tools). The screen is just locked. I can use the arrow keys to move the selection up and down the list, but because it doesn't scroll it's not possible to tell what is currently selected when it's off the screen.

I tested on your [demo page](http://amsul.ca/pickadate.js/index.htm) just to make sure it wasn't an implementation issue, and the problem occurs there too.

**Comment by DanielRuf** [comment]
We won't support IE8 in the future.
