### ISSUE TITLE
pickadate appears disabled in bootstrap 3

### ISSUE THREAD

**Issue by acornejo** [amsul/pickadate.js#474]
Given the ubiquity of bootstrap, it would be great if pickadate could work around it.

Namely, by setting the readOnly flag on the input element, bootstrap styles the element as being disabled (i.e. not editable). This is confusing for the users, since they are led to believe that the date cannot be changed (and in fact, it can!).

Setting the "editable" property fixes this problem, but creates another (now the field can be edited with the keyboard). A better fix would be to disable input of the field via javascript instead of using the css property.

Using readOnly on the CSS is misleading, since the input field is NOT readOnly, it can be changed, except that the change will be performed through the pickadate UI and not by typing.

PS: This issue is related to #443, except that I am reporting a problem on usability, where the reporter of #443 was instead trying to figure out how to disable "for real" the input.

**Comment by wilsonball** [comment]
@amsul Is there an update to your jsfiddle code? http://jsfiddle.net/P3s3h/ Not working.
