### ISSUE TITLE
Consider using transform for CSS animation

### ISSUE THREAD

**Issue by lifzgreat** [amsul/pickadate.js#475]
Because of how the hardware handles graphics processing, transform is much smoother (EXTREMELY noticeable in mobile browsing). Consider using transform for CSS animation!

See [fiddle](http://jsfiddle.net/6Wnw3/).

Basic idea:

div {
    -webkit-transform: translateY(200%);
    -webkit-transition: all .75s ease-out;
    transform: translateY(200%);
    transition: all .75s ease-out;
}

div.show {
    -webkit-transform: translateY(0);
    transform: translateY(0);
}

**Comment by zimt28** [comment]
Is this fixed? Opening pickadate is not really smooth

**Comment by kmiyashiro** [comment]
yeah, there's a lot of jank currently
