### ISSUE TITLE
Hidden Date Format Field Getting Wrong ID Attribute

### ISSUE THREAD

**Issue by myatt83** [amsul/pickadate.js#480]
I've been using pickadata for multiple version now and had an input element named 'txtProjectStartDate' with an id of 'txtProjectStartDate'. 

When i init the pickdadate I specify : 
            formatSubmit: 'yyyy/mm/dd',
            hiddenPrefix: 'hid_',
            hiddenSuffix: '_val',

and using Firebug could see a hidden form element being correctly generated:

input  type="hidden" id="hid_txtProjectStartDate_val" name="hid_txtProjectStartDate_val"

This seemed to work fine as expected. I believe I was using v 3.5.0. I recently upgraded to 3.5.3 and now the hidden element is being generated as:

input type="hidden" id="txtProjectEndDate_hidden" name="hid_txtProjectEndDate_val"

notice that the NAME attribute is correct, but the ID attribute is not.

**Comment by eaxexe** [comment]
Hi

I have a concern with this, fairly old, issue :)

In my project, I handle some form-data where I, for various reasons, do not submit the form, but rather go over the input fields and get each value.
I am interested in the hidden value, not the displayed one, and not having an id on the hidden field, makes this somewhat harder.

I have been able to add an id to the hidden field, by going through the _hidden object, and adding the id there, but as the API says: _If you have a valid reason for using this, please mention it in the Issues_

Would it be possible to add id's on the hidden value, back in?

Thanks in advance!
