### ISSUE TITLE
Can't get date picker to open programmatically

### ISSUE THREAD

**Issue by ianpetzer** [amsul/pickadate.js#481]
Hi,

I have an input element that I'm using pickadate on. It work beautifully when someone clicks the input form field and shows the date picker.

However, I've added a small calendar icon next to the date field, and I'd like the date picker to show when I click that icon.

When  I try to open the calendar in an onclick event handler, the calendar won't  open for example: http://jsfiddle.net/78Pv9/  ... I added picker.on('open' even handler which logs the fact that the calendar has been opened. This handler is definitely getting invoked but the calendar is not being displayed.

If I use the same code, but instead try to open the picker just after its been inserted then it displays without problem... for example..... http://jsfiddle.net/d59ky/

Any ideas?

**Comment by ciripp** [comment]
event.stopPropagation() fixed it for me too

**Comment by sharathrocks** [comment]
event.stopPropagation() worked! Thanks a lot for the suggestion

**Comment by AthulNair** [comment]
thanks @Anand1907

**Comment by Polovykh** [comment]
@amsul, thanks for this :*

**Comment by MDobariya** [comment]
event.stopPropagation() fixed it for me too

**Comment by guillermoromo** [comment]
thank you!
