### ISSUE TITLE
Cant keep Datepicker open onSet()

### ISSUE THREAD

**Issue by Anand1907** [amsul/pickadate.js#485]
Hi All,
         I am trying to keep datepicker open at all times, & should be closed only on custom click event.Currently , I am using picker.open() to open the picker.When I click on any dates inside the picker, the picker is closed & the value gets updated in textbox.I want to keep picker open.Is there any way to get this done ? Please help.

Cheers !

**Comment by mrDinckleman** [comment]
http://amsul.ca/pickadate.js/date/#close-on-action

**Comment by amsul** [comment]
Thanks @mrDinckleman :) .. This was added as of v3.5.5

Cheers!
