### ISSUE TITLE
Safari 7 Issue. The page does not load. Blocks Safari!

### ISSUE THREAD

**Issue by alensaqe** [amsul/pickadate.js#547]
The script blocks the page from loading in Safari In Mac book Pro 2011 with Safari 7 - 7.1 and in iPad Mini Safari. Could not reproduce the error. Test it out if you can. Was using the classic theme. Had to change the picker script to meet the deadline in my project. Just letting you know!

**Comment by amsul** [comment]
Closing this as unresponsive..
