### ISSUE TITLE
Wrong date being selected

### ISSUE THREAD

**Issue by leads** [amsul/pickadate.js#556]
Hi. I raised a bug on an Angular directive using this plugin. However I don't think it's an Angular thing, I think there is a bug with the latest version.

I downloaded the zip from GIthub and ran both index.htm and date.htm.

I *think* it's an issue when selecting an older date or a date several months in the future.

Select a date in the past, say 7th October 2014, and it selects October 8th (says so in the <input> and highlights the 8th when reopening the calendar). Tested in both Chrome and Firefox on Mac.

Anyone else getting this issue?

**Comment by cmwelsh** [comment]
This makes the current version totally useless... push out a new release... :+1:

**Comment by amsul** [comment]
This is fixed on master - feel free to point to there with Bower (or whatever your tool of choice).

3.5.5 will be tagged when the remaining issues are resolved: https://github.com/amsul/pickadate.js/milestones/3.5.5

Cheers.
