### ISSUE TITLE
Is it possible to add default time in datepicker

### ISSUE THREAD

**Issue by teethgrinder** [amsul/pickadate.js#560]
Hello I understand datepicker and timepicker is seperated but is it possible to add default times formatSubmit values
for eg I need to use start_date time 00:00 and end_date time 23.59 
```
  format: 'd mmmm, yyyy',
      formatSubmit: 'yyyy-mm-dd',
      hiddenPrefix: 'prefix__',
      hiddenSuffix: '__suffix',
      min: true,
      editable: true,
```
Thanks

**Comment by amsul** [comment]
Please read the docs http://amsul.ca/pickadate.js/date/ and guidelines https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports

These types of questions are better suited for StackOverflow. Cheers.
