### ISSUE TITLE
API set disable/enable date

### ISSUE THREAD

**Issue by elinlix** [amsul/pickadate.js#563]
Hi, 

We are setting our available dates upon the render according to this http://amsul.ca/pickadate.js/date.htm#disable-dates-all

We then try to use the picker.set() method to do the same/change the disabled dates but it won't work. Is the "[true, 
[list], 
[of], 
[dates]
]" 
syntax not accepted for the set.('disable') method? I've tried to disable them and then flip enabled and disabled but that won't work either. 

Is there any way to do this? Thank you in advance.

**Comment by amsul** [comment]
Closing as unresponsive..
