### ISSUE TITLE
Add ability to highlight days

### ISSUE THREAD

**Issue by Morantron** [amsul/pickadate.js#571]
Hi!

I have an use case where I need to highlight more than one day in the date picker (highlighting events, duration, recurring events, etc ). Right now I'm using a workaround to highlight specific dates, but it'd be nice if pickadate supported this out of the box.

Thanks!

**Comment by ibarral** [comment]
Hello!, I'm interested on your workaround to highlight specific dates :)

Can your explain me how you do it?

Thanks!

**Comment by Morantron** [comment]
@ibarral You can use the `data-pick` data attribute to figure out which date a cell is representing.

**Comment by ibarral** [comment]
ok, thanks for the tip! :)

**Comment by adinugro88** [comment]
var fullDaysArray = [
      [2018, 5, 1]
    ]
    fullDaysArray.forEach(function(date) {
      $('[data-pick=' + new Date(date[0], date[1], date[2]).getTime() + ']').addClass('pickadate--full')
    })

**Comment by adinugro88** [comment]
`  var fullDaysArray = [
      [2018, 5, 1]
    ]
    fullDaysArray.forEach(function(date) {
      $('[data-pick=' + new Date(date[0], date[1], date[2]).getTime() + ']').addClass('pickadate--full')
    })`

when i click next my highlight is missing
