### ISSUE TITLE
Month & Year Dropdown styling fix is missing again

### ISSUE THREAD

**Issue by eLburro** [amsul/pickadate.js#574]
In Oct. 13 2013 this fix was applied for version 3.3.0:
 #232: Dropdown styling tweaked.
https://github.com/amsul/pickadate.js/blob/dev/CHANGELOG.md

But this change has been reverted with the following commit:
"Commits on Apr 13, 2014" in https://github.com/amsul/pickadate.js/commits/dev/lib/themes/default.date.css

The display of the current pickadate dropdowns for month and year won't show correctly.
Is this going to be changed again or do I need to change it localy? 
Thank you for the great work.

**Comment by amsul** [comment]
This varies from one OS to another. There's no global solution so I've compromised to suit the majority case.

Cheers!
