### ISSUE TITLE
How can I consolidate pickadate initializer for multiple inputs on one page?

### ISSUE THREAD

**Issue by richbothe** [amsul/pickadate.js#580]
I have a page that has multiple inputs for pickadate and pickatime. How can I consilidate the jquery to where I have one call for pickadate and one call for pickatime?

Here is an example of the markup for pickadate:

    <div class="row">
        <div class="col-xs-3">
            <div class="form-group">
                
                <label><span class="required">*</span> Display Start Date</label>
                <input type="text" class="form-control select-date display-start-date" required>
                <i id="trigger1" class="calendar-icon"></i>
            </div>
        </div>
        <div class="col-xs-3">
            <div class="form-group">
                
                <label><span class="required">*</span> Display Start Time</label>
                <input type="text" class="form-control select-time display-start-time" required>
                <i id="trigger2" class="fa fa-clock-o fa-2x"></i>
            </div>
        </div>
        <div class="col=xs-6"></div>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <div class="form-group">
                
                <label><span class="required">*</span> Display End Date</label>
                <input type="text" class="form-control select-date display-end-date" required>
                <i id="trigger3" class="calendar-icon"></i>
            </div>
        </div>
        <div class="col-xs-3">
            <div class="form-group">
                
                <label><span class="required">*</span> Display End Time</label>
                <input type="text" class="form-control select-time display-end-time" required>
                <i id="trigger4" class="fa fa-clock-o fa-2x"></i>
            </div>
        </div>
        <div class="col-xs-6"></div>
    </div>

And here is the jquery:

    // Add Video - Display Start Date - pickadate 1
    var $input1 = $('.display-start-date').pickadate({
        format: 'mm/dd/yyyy',
        editable: true
    });
    var picker1 = $input1.data('pickadate');

    $('#trigger1').click( function( e ) {
        e.stopPropagation();
        e.preventDefault();
        picker1.open();
    });

    // Add Video - Display Start Time - pickatime 1
    var $input2 = $('.display-start-time').pickatime({
        interval: 15,
        editable: true
    });
    var picker2 = $input2.data('pickatime');

    $('#trigger2').click( function( e ) {
        e.stopPropagation();
        e.preventDefault();
        picker2.open();
    });

    // Add Video - Display End Date - pickadate 2
        var $input3 = $('.display-end-date').pickadate({
            format: 'mm/dd/yyyy',
            editable: true
        });
        var picker3 = $input3.data('pickadate');

        $('#trigger3').click( function( e ) {
            e.stopPropagation();
            e.preventDefault();
            picker3.open();
        });

        // Add Video - Display End Time - pickatime 2
        var $input4 = $('.display-end-time').pickatime({
            interval: 15,
            editable: true
        });
        var picker4 = $input4.data('pickatime');

        $('#trigger4').click( function( e ) {
            e.stopPropagation();
            e.preventDefault();
            picker4.open();
        });

**Comment by amsul** [comment]
Please read the guidelines: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports

These types of questions are better suited for StackOverflow. Cheers.
