### ISSUE TITLE
Disable specific dates from external file/input

### ISSUE THREAD

**Issue by pmeakins** [amsul/pickadate.js#605]
Is it at all possible to exclude a specific set of dates using an input from something like JSON, i'e disbale all bank holidays.

In my case I have an events system which when 'a day if full' i want to be able to disable that date(s)

Many thanks - and very cool js

**Comment by jgillman** [comment]
The best option would be for you to write a function that converts your JSON into the format that pickadate expects. You can find the formats here: http://amsul.ca/pickadate.js/api/#method-set-disable-enable

**Comment by amsul** [comment]
@pmeakins yup, @jgillman is right.. load the JSON and use the `set` method to `disable` dates as you need.

Cheers
