### ISSUE TITLE
Datepicker not showing after pressing a button

### ISSUE THREAD

**Issue by nickgeys** [amsul/pickadate.js#607]
Dear,

I've put this awesome datepicker on my asp.net page.
all works well at page load but when I Press any button, the datepicker just doesn't show anymore.
Even more strange: there is no code behind the button (added 'resetdatepicker to start it again):  <asp:button runat="server" id="btnManualClockin" CausesValidation="false" Text="Manueel inklokken" OnClientClick="resetDatePicker();" />

(I get the same result when i'm using a normal html button).

After clicking the button, the page console does not give me any errors.

I tried starting it again with this code (via button onclientclick event).
  function resetDatePicker() {
            alert("test");
            var $input = $('.datepicker').pickadate()
            var picker = $input.pickadate('picker')
            picker.start()
            alert("test2");
        }

but that gives me an error in the console:
Uncaught TypeError: undefined is not a function
resetDatePicker
onclick

Extra info: i'm using an ASP.net masterpage and jquery-1.8.2.min.js

anybody got an idea what is happening?

**Comment by amsul** [comment]
Please read the guidelines: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports

These types of questions are more suitable on StackOverflow. Cheers!
