### ISSUE TITLE
Date limits parameters ('min' and 'max') display the wrong month.

### ISSUE THREAD

**Issue by Joel-Maizonnier** [amsul/pickadate.js#613]
I have an instance where I need to limit dates that the user can selected within the popup control.

I have noticed that no matter what format I change when providing these dates during construction, that the limited range has been incremented by one month.

For example 2009/01/10 to 2009/02/20 will be show users they can selected a date within the following limits:

2009/02/10 to 2009/03/20

This effects are also present on the demo site.

**Comment by amsul** [comment]
That's how dates in javascript work. Please read the docs and the numerous issues created previously: http://amsul.ca/pickadate.js/date.htm#picker
https://github.com/amsul/pickadate.js/issues/435 
https://github.com/amsul/pickadate.js/issues/224
https://github.com/amsul/pickadate.js/issues/334

Cheers.
