### ISSUE TITLE
Font Awesome CDN Doesn't Play Well

### ISSUE THREAD

**Issue by SirSteve** [amsul/pickadate.js#620]
Using font awesome CDN from maxcdn, I get unexpected behavior with the hover with Pickadate.

//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css

**Comment by SirSteve** [comment]
I also verified it does the same unexpected behavior a local instance of Font Awesome.

**Comment by leesalminen** [comment]
What unexpected behavior exactly?

I am experiencing an issue with the time picker being blank when focused. Could be totally unrelated, but I am including that same file in my project.

**Comment by SirSteve** [comment]
We found the exact issue... the spinner font (fa-spinner) does not play well with the timepicker. Test it for yourself.

**Comment by amsul** [comment]
@SirSteve please provide a working example of the bug on JSBin.
