### ISSUE TITLE
Close button not show

### ISSUE THREAD

**Issue by nfloresv** [amsul/pickadate.js#625]
The documentation says that there is an option for a close button, but it doesn't show.

This bug also happend in the webpage where it show the setting but the buttons doesn't show.
![button close](https://cloud.githubusercontent.com/assets/3127337/5926821/c0818d0c-a64c-11e4-9150-580097e37cae.png)
![picker button close](https://cloud.githubusercontent.com/assets/3127337/5926823/ca4dc0b2-a64c-11e4-85e0-a707e63ef921.png)

**Comment by amsul** [comment]
The `gh-pages` branch had been temporarily reverted to an older release. It's fine now: http://amsul.ca/pickadate.js/date/#buttons

Cheers.
