### ISSUE TITLE
Affecting one picker from another

### ISSUE THREAD

**Issue by netm** [amsul/pickadate.js#626]
Not an 'issue' but a cry for help.. How to seed one picker from another?

	var endDate = $('.end-date .datepicker').pickadate({
	    formatSubmit: 'yyyy-mm-dd'
	})

	// Would like date from startDate copied over to endDate on change
	var startDate = $('.start-date .datepicker').pickadate({
	    formatSubmit: 'yyyy-mm-dd',
	    onSet: function(endDate) {
	        console.log('Want to set endDate to - ' + this.get('select', 'yyyy/mm/dd'));
	        endDate.set('select', this.get('select')); // This line is wrong :-(
	    }
	})

**Comment by Golmote** [comment]
Hi there.
Does `this.get('select').obj` help? It normally returns a Date object so it should be a valid input fot setting select.

**Comment by netm** [comment]
Sorted! Thanks! I used that tip and also added this line..

     var picker_end_date = endDate.pickadate('picker');

Working looks like this...
    
    // End date
    var endDate = $('.end-date .datepicker').pickadate({
        formatSubmit: 'yyyy-mm-dd'
    });
    var picker_end_date = endDate.pickadate('picker');
    
    // Start date, onset change enddate
    var startDate = $('.start-date .datepicker').pickadate({
        formatSubmit: 'yyyy-mm-dd',
        onSet: function(endDate) {
            //console.log('Want to set endDate to - ' + this.get('select', 'yyyy/mm/dd'));
            picker_end_date.set('select', this.get('select').obj);
        }
    })
