### ISSUE TITLE
Year and Month truncated

### ISSUE THREAD

**Issue by sebasonic** [amsul/pickadate.js#628]
Visible on :
http://amsul.ca/pickadate.js/date/#accessibility-labels
with Firefox 35.0.1 & Chromium 39.0.2171.65 
Ubuntu 14.04 (64-bit)
The visibles values for the month and the year drop-down list are truncated.
Solution : in default.date.css, just set the height to 2.5em like that :

.picker__select--month,
.picker__select--year {
  height: 2.5em;
}

cheers

**Comment by amsul** [comment]
It’s different for each OS. Not something that can be solved universally - so not going to worry about this :)

Cheers.

**Comment by sebasonic** [comment]
It's the same on Android for me

2015-02-09 1:40 GMT+01:00 amsul <notifications@github.com>:
