### ISSUE TITLE
When window re-focused pickadate pops up

### ISSUE THREAD

**Issue by thanpolas** [amsul/pickadate.js#630]
* Initialize pickadate
* Focus on another window or tab
* Focus back to window
* Calendar pops up

Happens on [demo](http://amsul.ca/pickadate.js/) page too so this must be a new issue...

**Comment by thanpolas** [comment]
this goes back to 3.4.0, didn't try earlier versions

**Comment by amsul** [comment]
This has been mentioned several times before. Please read here: #160

Cheers.
