### ISSUE TITLE
Best way to count days between fromdate and todate?

### ISSUE THREAD

**Issue by qbussrl** [amsul/pickadate.js#632]
Hallo,

can you help me to see what is the best way to count days between fromdate and todate in pickadate?

Thanks in advance

**Comment by amsul** [comment]
Such questions belong on StackOverflow: http://stackoverflow.com/search?q=pickadate

[Guidelines](https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports).

Cheers.
