### ISSUE TITLE
How do you initiate this?  I can't even replicate the demo

### ISSUE THREAD

**Issue by xtianus79** [amsul/pickadate.js#633]
I am having a terrible time with this.  How do you properly initiate this to load?  the documentation is sparse.

**Comment by ashwebb** [comment]
Make sure you have all the javascript and css file paths called. Then it's as simple as adding .timepicker or .datepicker to a select input. Then call $('.timepicker').pickatime(); or $('.datepicker').pickadate(); This will initiate the input with the default settings.

**Comment by andrewkatz** [comment]
I think there's a bug in 3.5.5 that could be causing your issues. Since updating to 3.5.5 from 3.5.4, the initializer is no longer working.

**Comment by winious** [comment]
It looks like the check for transitions is causing issues for us.
https://github.com/amsul/pickadate.js/blob/master/lib/picker.js#L26. Maybe it has something to do with the compressed version?

**Comment by mrserge** [comment]
I also have no clue, what are the javascript and css files I need to add in the <head>. After downloading source, there is 100+ files. It would be just megastupid, if I need to call them all. Would be absolutely normal to add some simple lines of code as a boilerplate.

**Comment by bgdz** [comment]
Replace [path to pickadate folder] with your path.
```html
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="cache-control" content="no-cache">

<title>basic pickadate datepicker</title>
<link href="[path to pickadate folder]/lib/themes/default.css" rel="stylesheet" id="theme_base">
<link href="[path to pickadate folder]/lib/themes/default.date.css" rel="stylesheet" id="theme_date">

<!--[if lt IE 9]>
  <script>document.createElement('section')</script>
<![endif]-->
</head>

<body>
<label> input something here: </label>
<input
      id=""
      name=""
      class="datepicker"
      type="text"
      
        placeholder="Test"
      
      
      
      >
<script src="[path to jquery, change to match your version or use the google version]/jquery-1.11.2.min.js"></script><!-- latest available here: http://jquery.com/download/ -->
<script src="[path to pickadate folder]/lib/picker.js"></script>
<script src="[path to pickadate folder]/lib/picker.date.js"></script>
<script src="[path to pickadate folder]/lib/legacy.js"></script>

<script>
// Initialize the basic datepicker

$( '.datepicker' ).pickadate({

    // Work-around for some mobile browsers clipping off the picker.
    onOpen: function() { $('pre').css('overflow', 'hidden') },
    onClose: function() { $('pre').css('overflow', '') }
})
</script>

</body>
</html>

```

**Comment by amsul** [comment]
Such questions belong on StackOverflow: http://stackoverflow.com/search?q=pickadate

[Guidelines](https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports).

Cheers.
