### ISSUE TITLE
3.5.5 seems to be broken

### ISSUE THREAD

**Issue by csloisel** [amsul/pickadate.js#634]
Getting:

`Uncaught TypeError: Cannot read property 'style' of null`

On picker.js line 26:
https://github.com/amsul/pickadate.js/blob/3.5.5/lib/picker.js#L26

Using Chrome 40.0.2214.111 (64-bit)
on OSX Yosemite 10.10.2

**Comment by snocorp** [comment]
Seeing the same issue.

I would suggest something like:

```js
var supportsTransitions = function() { return document.body.style.transition != null; }
```

Then call that function in the one place that uses it since the body will be initialized by then.

**Comment by IamNaN** [comment]
Wow, thanks. I just spent about an hour tracking this down myself. I'm new to bower so I thought that is where the problem was... nobody expects the Spanish... er, the package to be broken.

**Comment by ivanyv** [comment]
This is also present in 3.5.2

**Comment by dazhbog** [comment]
this worked for me too! thanks!

**Comment by lucastschmidt** [comment]
+1, just updated here, and it stopped working

**Comment by lvpro** [comment]
Yep, broken.  Same behavior here.

I rolled picker.js back to 3.5.0 and all is working again.

**Comment by eliotsykes** [comment]
Only tried in Chrome: pickadate 3.5.5 is working by moving the `<script>` tag from the `<head>` to immediately before the **closing** `</body>` tag. (Admittedly not ideal, just a workaround.)

**Comment by rdetert** [comment]
Yeah, including the pickadate js files at the end of the page works for me too.

**Comment by amsul** [comment]
Solution is mentioned here: https://github.com/amsul/pickadate.js/issues/667#issuecomment-85983322

Fixing in the next release.
