### ISSUE TITLE
Is there a way to set the time input to have an initial value

### ISSUE THREAD

**Issue by Jordan4jc** [amsul/pickadate.js#635]
I see on the datepicker I can use data-value with a string to have a date pre populated, but I don't see something similar for the time picker. How can I get this to work?

**Comment by cmwelsh** [comment]
Here's what I do:

    // Initialize picker
    var $timeInput = $('.time-input');
    $timeInput.pickatime(config);

    // Get picker instance
    var timePicker = $timeInput.pickatime('picker');

    // Set initial value
    var initialValue = 960; // 960 minutes past midnight = 4:00pm
    timePicker.set('select', initialValue);

**Comment by Jordan4jc** [comment]
Thanks! Though in the future it would be cool so see the ability to do something similar to what the date picker does.
