### ISSUE TITLE
From To

### ISSUE THREAD

**Issue by polikin** [amsul/pickadate.js#637]
It is possible to show the calendar with the From To option?

your example: http://codepen.io/amsul/pen/nGckA

**Comment by dswebdotnet** [comment]
Yes, the external scripts on the pen are broken, so they're not showing up. Put picker.js and picker.date.js on your own server or link from elsewhere and it will work. Click the cog icon in the JS code section to see the broken paths.

**Comment by polikin** [comment]
thanks

**Comment by amsul** [comment]
The links to the scripts have been fixed. Cheers!
