### ISSUE TITLE
Location of the Calendar popup

### ISSUE THREAD

**Issue by sscotti** [amsul/pickadate.js#644]
Is there a way to position it directly below the input field that it is attached to?  In my default setup it is located at the bottom of the browser window.  You have to move the mouse to the bottom of the page to pick a date.  Ergonomically not the best arrangement.

**Comment by amsul** [comment]
Please read the [Guidelines](https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports).

If you can reproduce it as an isolated bug with a live example, then it is something I can look into.

Cheers.
