### ISSUE TITLE
When maximize my browser, pickadate appears again

### ISSUE THREAD

**Issue by pedropcruz** [amsul/pickadate.js#646]
I am new on GitHub, but i have a question to do...

First - When i open my calendar like this: http://prntscr.com/6ai3np he appears well, nice and clean, but when i minimize my window (of the browser) and maximize then, he appears again without clicking on my icon with an "a". I will demonstrate my code:

http://jsbin.com/hirodi/1

What i'm doing wrong?

**Comment by pedropcruz** [comment]
Sorry, i have found that issue. #160

Thanks.

**Comment by amsul** [comment]
No worries. Cheers!
