### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by glassresistor** [amsul/pickadate.js#649]
We are trying to use this library with browserify.  It looks like you added a bunch of fixes since Dec could you publish them to NPM.

Will the changes in 3.5.5 make it work with browserify?

**Comment by lucastschmidt** [comment]
It doesnt look like it can work with browserify, since it requires like 3 files, and there are css stuff (that could actually be included in your own ... )

But, it would be great if this had support. +1

**Comment by glassresistor** [comment]
So if you package the css with it I normally just include the css or less
files from the node_modules directly.
What are the files that browserify has an issue with?  We currently have it
working in our system just fine.

On Wed, Mar 11, 2015 at 12:01 PM, Lucas Schmidt <notifications@github.com>
wrote:

> It doesnt look like it can work with browserify, since it requires like 3
> files, and there are css stuff (that could actually be included in your own
> ... )
>
> But, it would be great if this had support. +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amsul/pickadate.js/issues/649#issuecomment-78346666>.
>



-- 
Mikela

**Comment by glassresistor** [comment]
The only issue is that the most up to date version isn't in npm :)

On Wed, Mar 11, 2015 at 12:10 PM, Mikela Clemmons <glassresistor@gmail.com>
wrote:

> So if you package the css with it I normally just include the css or less
> files from the node_modules directly.
> What are the files that browserify has an issue with?  We currently have
> it working in our system just fine.
>
> On Wed, Mar 11, 2015 at 12:01 PM, Lucas Schmidt <notifications@github.com>
> wrote:
>
>> It doesnt look like it can work with browserify, since it requires like 3
>> files, and there are css stuff (that could actually be included in your own
>> ... )
>>
>> But, it would be great if this had support. +1
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/amsul/pickadate.js/issues/649#issuecomment-78346666>.
>>
>
>
>
> --
> Mikela
>



-- 
Mikela

**Comment by lucastschmidt** [comment]
Humm, you require each javascript individually, like ''require('pickadate/file')?

**Comment by glassresistor** [comment]
Sorry yeah we agree it works with browserify please just publish to npm

On Wed, Mar 11, 2015 at 12:48 PM, Lucas Schmidt <notifications@github.com>
wrote:

> Humm, you require each javascript individually, like
> ''require('pickadate/file')?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amsul/pickadate.js/issues/649#issuecomment-78355411>.
>



-- 
Mikela

**Comment by amsul** [comment]
Sorry for the delay on this. It has been published to npm now.

Cheers!
