### ISSUE TITLE
Infinite loop when using years in the range [0, 99] for max date restriction

### ISSUE THREAD

**Issue by stevenfan** [amsul/pickadate.js#650]
This causes an infinite loop on Chrome 40.0.2214.115 (64-bit), because during the search for a valid date after updating the max, the search year always starts at 1999, instead of 99. This could be fixed by always using Date objects for intermediate date calculations instead of arrays of integers.

http://codepen.io/anon/pen/xbJYQQ

**Comment by amsul** [comment]
I don't understand. You've parsed the date: `moment("0099-5-5", "YYYY-MM-DD")` - which is clearly not 1999. So when you call `m.toDate()`, it will return a date with the year as 99.

**Comment by stevenfan** [comment]
This has nothing to do with the date parsing - it has to do with the infinite loop in certain browsers, which happens because of the date parsing being different. The reason why the issue only affects certain browsers is because Javascript's Date() has different behaviour in different browsers.
