### ISSUE TITLE
Inline usage of the date picker

### ISSUE THREAD

**Issue by olivierlesnicki** [amsul/pickadate.js#651]
We've managed to render the date picker as an inline calendar. However, once the calendar is rendered on the page and the user first clicks on it, his scroll position jumps by a random amount.

It feels like the library isn't optimized for inline usage. Any recommendations? Or what could be the reason why the page scrolls when the calendar is focused?

**Comment by demogorgorn** [comment]
olivierlesnicki, could you please explain how you achieved to make pickadate inline? Thank you!

**Comment by olivierlesnicki** [comment]
I have liaised with the team member who did this implementation first - apparently it was using a previous major version of the plugin.

Additionally I've found out that the scroll position jump only happens on Chrome (and not Firefox) and therefore might not be related to the plugin.

For that reason this issue can be closed.

**Comment by bsgies** [comment]
@olivierlesnicki Please share your code how you've achieved the inline experience?
