### ISSUE TITLE
TypeError: document.body is null

### ISSUE THREAD

**Issue by ozgun** [amsul/pickadate.js#661]
After upgrading from 3.5.0 to 3.5.5 we started getting the following error: 

```
TypeError: document.body is null 
ReferenceError: Picker is not defined
ReferenceError: Picker is not defined
```

The browser is Firefox 35 on Linux.

**Comment by ozgun** [comment]
Downgrading from 3.5.5 to 3.5.4 fixed the problem.

**Comment by RobinJ1995** [comment]
Same thing... Seems like they didn't test properly.

**Comment by mikeslim7** [comment]
I think you will experience this if you declare the js files within the <head> section. Try to declare your js after closing the <body> section. I have just tried and the error does not appear anymore.

**Comment by criography** [comment]
Quick temp fix for me was to amend line 26 in picker.js from:
`var supportsTransitions = document.body.style.transition != null`

to:
`var supportsTransitions = (document.body || document.documentElement).style.transition != null`

**Comment by amsul** [comment]
@criography that’s correct. Also mentioned here: https://github.com/amsul/pickadate.js/issues/667#issuecomment-85983322

Fixing in the next release.

**Comment by criography** [comment]
Sweet. Thanks!
