### ISSUE TITLE
problem with the display of the popup

### ISSUE THREAD

**Issue by ambicoder** [amsul/pickadate.js#663]
I am trying to use the plugin but I am facing a problem when I click the input element - look this image to see how the popup that displays the times looks like http://1drv.ms/1I00pY7 just look at the image

**Comment by rdetert** [comment]
I've noticed something similar. Are you overriding the default table css anywhere else?

**Comment by amsul** [comment]
Please read the [Guidelines](https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports).

If you can reproduce it as an isolated bug with a live example, then it is something I can look into.

Cheers.
