### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by oytunistrator** [amsul/pickadate.js#667]
```
var supportsTransitions = document.body.style.transition != null 
```

line giving this error: Uncaught TypeError: Cannot read property 'style' of null

**Comment by llernestal** [comment]
I also got this error when loading picker.js in `<head>`.

Shouldn't

    var supportsTransitions = document.body.style.transition != null

be

    var supportsTransitions = document.documentElement.style.transition != null

?

**Comment by amsul** [comment]
@llernestal you are correct. Fixing this in the next patch.
