### ISSUE TITLE
Disable time dynamically

### ISSUE THREAD

**Issue by hugorodrigues182** [amsul/pickadate.js#676]
How could i disable time dynamically. Example: I do request a via ajax and want these schedules that returned via json are disabled. Thanks

**Comment by dahal** [comment]
+1

**Comment by dahal** [comment]
Upon some research, I found that its possible to set the time dynamically. My issue was radio button, with multiple options. And I wanted to be able to set different `min` date when different radio buttons are checked. 

@hugorodrigues182 you might wanna take a look at : http://amsul.ca/pickadate.js/api/#method-set or even http://jsfiddle.net/3gtvz/2/. Hope it helps.

**Comment by hugorodrigues182** [comment]
got it , thank dahal
