### ISSUE TITLE
picker_holder overlaid on top of my navigation buttons

### ISSUE THREAD

**Issue by lbendat** [amsul/pickadate.js#678]
I have tried playing with the container option - all to no avail.  The picker_holder isn't hidden at the bottom of the page.  Mind you, I'm more of a back-end guy; so I struggle a bit with CSS.  Anybody have any thoughts?  

![screen shot 2015-04-10 at 6 44 26 pm](https://cloud.githubusercontent.com/assets/4633348/7099751/b111d4aa-dfb1-11e4-9003-27a13f94f7b2.png)

**Comment by Jivebunny** [comment]
Hey,

How did you get rid of the line? Running into the same issue and can't seem to find the css for it.
