### ISSUE TITLE
Consolidate lib/translations/fa_IR.js and fa_ir.js

### ISSUE THREAD

**Issue by steveyken** [amsul/pickadate.js#685]
Looks like you've got two translation files for the same language:

* lib/translations/fa_IR.js
* lib/translations/fa_ir.js

I'm using pickadate via ember-cli and bower/broccoli build system which gives me the following error on the latest pickadate version.

```Error: Merge error: conflicting capitalizations:
pickadate/lib/translations/fa_IR.js in <path>/tmp/funnel-dest_CDIUjl.tmp
pickadate/lib/translations/fa_ir.js in <path>/tmp/funnel-dest_CDIUjl.tmp
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.```

**Comment by mcm-ham** [comment]
It looks like two identical commits in source history just different file casing https://github.com/amsul/pickadate.js/commit/8bf81ac381457fa13a214e063e2b8dd9ea0b1c13 https://github.com/amsul/pickadate.js/commit/3193dbf49783e7275aa077ca289323aed39e34d5

**Comment by mohamnag** [comment]
they are definitely the same, do you plan to fix this soon by removing one so that builds can run normally again?
