### ISSUE TITLE
no closing in Firefox with surrounding label-tag

### ISSUE THREAD

**Issue by Gregor-Agnes** [amsul/pickadate.js#686]
First: thx a lot fo this great picker :+1:  :)

In Firefox the picker doesn't close if there is a surrounding label tag. Neither on click on "close" nore onSelect or onClear.

In Chrome only the closeOnSelect and the closeOnClear don't work.

Closing with "esc" key does work.

I think it has something to do with the focus, but I didn't figure out what could be changed.

Regards

**Comment by massic80** [comment]
I didn't notice this on desktop Firefox, but when closing the date picker in FF Mobile I need to tap twice.
Do you think it's the same trouble?

**Comment by Gregor-Agnes** [comment]
Hi,

hm, as it happens I just used the latest version on a new installation and everything works fine. I didn't figure, what is the cause.

Maybe double selectors (classes or ids) on the page? Just a shot in the dark :)

**Comment by amsul** [comment]
A `label` performs another focus event..in turn opening it again. There's a workaround mentioned in the docs: http://amsul.ca/pickadate.js/date/#container
