### ISSUE TITLE
Sporadic loading of plugin. 

### ISSUE THREAD

**Issue by cargix1** [amsul/pickadate.js#694]
I've got a very strange problem occurring. Sometimes the plugin decides to work and other times it doesn't. 

I've added some console.log()'s to picker.js picker.date.js and picker.time.js and all are firing off as expected. Also if I check $.fn.pickadate to see if it exists it does. But then when I actually call $('.datepicker').pickadate() i'm getting:

Uncaught TypeError: jQuery(...).pickadate is not a function

If I refresh the page then the majority of times it all works as expected. But the odd occasion it doesn't. 

Any suggestions on what this could be?

**Comment by noleafclover614** [comment]
I also get this message.

**Comment by LovelyHorse** [comment]
I get the same issue.

**Comment by amsul** [comment]
Read the guidelines before opening a new issue: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md

If you can't create a reduced test case where this bug is reproducible, then it's something else in your project causing this issue.

Cheers.
