### ISSUE TITLE
custom classes for specific dates or date ranges

### ISSUE THREAD

**Issue by massimocolella** [amsul/pickadate.js#701]
Hi,
just checking if this change 
https://github.com/magleff/pickadate.js/commit/2076d3422b1eb1a3f7f0344934b9a3000983c3c4
has been committed. I was looking in the docs, but I cannot find anything related to "set custom class for specific dates".
Tried 
picker.set('class', 'pickadate--full', [2015,4,25] );
but it seems not a defined action.
I would like to set classes for specific enabled and/or disabled dates.
I tried implementing this solution:
https://github.com/amsul/pickadate.js/issues/259
but I should trigger any changes to the datepicker in order to show colored dates each time the user clicks on the calendar.
any suggestion?
thanks in advance.

**Comment by ericmwalsh** [comment]
Any update on this issue?

**Comment by amsul** [comment]
Let's keep the convo in the original issue: https://github.com/amsul/pickadate.js/issues/701
