### ISSUE TITLE
ALT-TAB opens picker - Bug

### ISSUE THREAD

**Issue by defenderjim** [amsul/pickadate.js#710]
Have a browser and another window open, like "WIndows Explorer", GIT Hub, NetBeans, etc.
Then using the example page, //http://amsul.ca/pickadate.js/,
Click on a date or time, picker comes up. select a date or time.
Use  ALT-TAB to switch to another application.
Date/Time picker opens up and should not.

**Comment by darianbr** [comment]
Same happening to me in Safari and Chrome on Mac

**Comment by leads** [comment]
Seems to only happen with the default theme and not the classic theme?

**Comment by defenderjim** [comment]
Don't know, haven't tested all scenarios.

**Comment by amsul** [comment]
Duplicate of #160
