### ISSUE TITLE
Infinite loop when all days of week are disabled

### ISSUE THREAD

**Issue by stevenfan** [amsul/pickadate.js#723]
When all days of week are disabled, the the code goes into an infinite loop looking for a valid date:

http://codepen.io/anon/pen/zGRxGg

This can happen for example, if dynamically setting the days of week to be disabled via user input.

While this isn't strictly a bug in pickadate, taking some precaution on the supplied value to avoid infinite looping might be handy - the problem was actually difficult to debug for us since Chrome was rendered totally unresponsive.

**Comment by amsul** [comment]
Won't be a problem in v5 🙏
