### ISSUE TITLE
IE9 Clear/Close Button not closing picker

### ISSUE THREAD

**Issue by designchief** [amsul/pickadate.js#726]
Hi Amsul,

I’m wondering if you can help me please,
I have used your Pickadate & Pickatime on a site,
but the client has just noticed an issue with the Clear button not closing the Pickadate,
which is making it impossible for IE9 users to complete the form.

This project had been started back in 2013, so it was using an old version of your JS,
so I recreated my original design demo, and updated the JS to the current version (legacy is also included).
I thought that this had solved the issue, but it is not fully solved,
as now it has turned into a intermittent problem.

Looks like now, the Clear button will work the first time,
but if you try and do this a few times in the same field you get the same issue.

The Close button was working for me in my tests in IE9 which would be a get out for users,
but sadly the client has come back to me saying that in their tests in IE9 (running on Citrix),
the Close button is not closing the Pickadate either which is making the form unusable again.

Here is the link to my demo:
http://my-allianz-fa-02.designchief.ie/claim-notification.html

The sequence is
- scroll down to "Please select a claim option" dropdown,
- select Accident/Incident option
- In the Accident Details fieldset you will find the "Date of Accident" Pickadate field (Pickatime also used in the field next to this one)
- Everything works as expected apart from IE9 where you can select a date ok, but when you re-enter the field and try to Clear the info, the Pickadate flickers (disappears and then reappears) and then cannot be closed.

The site was built using Zurb Foundation 4.3.2 and is using jQuery 1.10.2.

I hope you can take the time to have a look at this for me,
as I cannot see anything else that might be causing the issue.

Many thanks,
Kieran Mahon.

![screen shot 2015-07-03 at 09 04 45](https://cloud.githubusercontent.com/assets/3732548/8495103/c60ad544-2162-11e5-9513-136d0eb7d8e4.png)

**Comment by designchief** [comment]
Hi guys,

anyone has any suggestions for this one?
under a bit of time pressure!!

thanks, Kieran.

**Comment by amsul** [comment]
Issues like these are better suited on StackOverflow as mentioned in the Contributing guide: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports
