### ISSUE TITLE
IE8 support not working well

### ISSUE THREAD

**Issue by craigrs84** [amsul/pickadate.js#730]
I'm seeing rendering issues when loading on IE8.  For example, some elements of the popup calendar are visible on page load.  It also seems like not all of the styled elements are being loaded / displayed properly.

I'm including the legacy.js file in my HTML but it doesn't seem to help.

Also, I'm curious, is this plugin supposed to work with IE7 as well?

**Comment by amsul** [comment]
IE8 support is going to be dropped very soon. We’re not going to spend much time fixing these legacy issues — especially when it comes to styling.
