### ISSUE TITLE
Show entire month even if all disabled

### ISSUE THREAD

**Issue by ghost** [amsul/pickadate.js#731]
Hello,

When I disabled dates from 07/28/2015 to 08/08/2015, the date picker open  on August with 08/09/2015 highlighted and if I make a console.log of 
this.get('highlight', 'yyyy-mm-dd')
I get 2015-07-07 
Is this a normal behavior of pickadate.js? How can I display a month even if all the dates are disabled?

Best regards
Fanny

**Comment by amsul** [comment]
No way in v3 - won't be a problem in v5
