### ISSUE TITLE
Set the min and maximum

### ISSUE THREAD

**Issue by RosiersRobin** [amsul/pickadate.js#736]
Hi,

When I try to set a min and max year, It doesn't work well...

So I want to get a first year selection of 1970 and then the maximum year must be the current year, how can I do this? Screen: http://prntscr.com/7tqtea

So that dat moest end with 2015 (for now) and begin with 1970. How can I do this?

Kindest regards,
Robin.

**Comment by Advil-Robin** [comment]
Ohw, also when I set the formatSubmit to formatSubmit: 'Y-m-d 00:00:00', It doesn't give the year with it? I really need to get this working...

**Comment by amreshpandey** [comment]
http://amsul.ca/pickadate.js/date/#disable-dates-use-arrays

In examples given under this link for min and max date doesn't work.
Minimum is set to 20 March but show maximum upto 20 April
and max is set to 14 July, goes upto 14 August.

**Comment by bkonia** [comment]
Yes, this is a bug. It allows the user to select a date up to one month LATER than the specified max date.

**Comment by bkonia** [comment]
I'm wondering why this issue was closed, since the bug still exists. You can even see it in the [demo on this website](http://amsul.ca/pickadate.js/date/#limits). The max date is specified as 2015-07-14, yet the control allows the user to select up to 2015-08-14.

**Comment by Advil-Robin** [comment]
Reopend since the bug still exists, however this bug was repored since 2015 and nothing has been done with it.

**Comment by DarthSonic** [comment]
For "new Date()" in JavaScript month parameter is zero-based index, so for 2015-07-14 you have to set new Date(2015, 6, 14).

**Comment by DanielRuf** [comment]
Exactly, and this is why this is not a bug.
