### ISSUE TITLE
Merging the files into one. 

### ISSUE THREAD

**Issue by rgfx** [amsul/pickadate.js#743]
I would like to combined all the js files, but there is some kinda require script running. Not sure how to bypass this to just have one minified picker.js file. Any assistance would be great. 

```
<script src="/fantasy/assets/picker.js"></script>
<script src="/fantasy/assets/picker.date.js"></script>
<script src="/fantasy/assets/picker.time.js"></script>
<script src="/fantasy/assets/legacy.js"></script>
```

**Comment by DanielRuf** [comment]
Do you mean concatenation?
Using just one big file is not the ideal solution anymore.
Do you have any issues to use one concatenated file?

**Comment by DanielRuf** [comment]
Ok so this issue is not relevant anymore I guess?

**Comment by rgfx** [comment]
It could be, am not using your plugin at the moment. Its great plugin, surely will swing back around someday. Hope your reply comes faster than 3 years the next time :)

Feel free to close this issue, thanks.

**Comment by rgfx** [comment]
It could be, am not using your plugin at the moment. Its great plugin, surely will swing back around someday. Hope your reply comes faster than 3 years the next time :)

Feel free to close this issue, thanks.

**Comment by DanielRuf** [comment]
> Hope your reply comes faster than 3 years the next time :)

I've joined the project just a few days ago ;-)

**Comment by DanielRuf** [comment]
Closing the issue as not relevant at the moment. If you have any issue with a specific setup with current bundlers and solutions let us know and we will take a look at it.
