### ISSUE TITLE
datepicker.get('view') Returns incorrect date every time.

### ISSUE THREAD

**Issue by Dayjo** [amsul/pickadate.js#753]
You can replicate this on the API page of the website here; http://amsul.ca/pickadate.js/api/#method-get-start

If you look at the console, the date is always the 1st no matter what you set the datepicker to.

![](http://c.dayjo.me/image/0A0W2U2w3e2E/Screen%20Recording%202015-08-18%20at%2012.08%20pm.gif)

Appears to work ok on time picker.

**Comment by amsul** [comment]
@Dayjo that's what the `view` date is: https://amsul.ca/pickadate.js/api/#method-get

You might be thinking of the `select` date.
