### ISSUE TITLE
Errors when using jquery 1.7.2

### ISSUE THREAD

**Issue by razz3251** [amsul/pickadate.js#754]
Using modal - clicking on any of the buttons bottom (today, clear etc) - results in error. Updating jquery version fixes this but this is supposed to work in jquery 1.7+

**Comment by mexitalian** [comment]
I am having the same issue. v1.7.2, looking for a workaround as I cannot change the jQuery version.

**Comment by mexitalian** [comment]
On line:731 of picker.js there is a conditional that uses $.contain.
When the *today*, *clear* and *cancel* buttons are clicked the typeof var being passed is incorrectly coming through as *string* and not *object* and the execution stops there.
Have wrapped the conditional with
```javascript
if ( typeof activeElement == "object" ) { … }
```
Now the execution continues, jumping over this check (as it is not suitable) and onto fulfilling it's function.
@razz3251 hope that's of use to you.

**Comment by razz3251** [comment]
great work - thanks mexitalian ;)

**Comment by rkingy** [comment]
Thanks, this helped us out!

How do we get this update into the main branch?

**Comment by DanielRuf** [comment]
jQuery 1.x is not officially supported anymore.
