### ISSUE TITLE
Integrating both the date and time

### ISSUE THREAD

**Issue by MajidCS** [amsul/pickadate.js#766]
Hi , 

I wish I could be merged both the date and time in one model.

Like this is :

http://i.imgur.com/E44d8GI.png  OR   http://i.imgur.com/OmeFp4D.png OR http://i.imgur.com/CpKBmBm.png

I wish if you can modified design for time, because the design is not good with page.

Like this is : 

http://i.imgur.com/zNjHopF.png

thank you,

**Comment by wdog** [comment]
me too :smile:

**Comment by amsul** [comment]
Read the guidelines before opening a new issue: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md

Duplicate of https://github.com/amsul/pickadate.js/issues/267
