### ISSUE TITLE
Setting a minimum date goes 1 month later

### ISSUE THREAD

**Issue by ssstofff** [amsul/pickadate.js#768]
the minumum date is 1 month miscalculated.
min: [2015,9,14] gives the calendar for October instead of September

http://screenshot.s.emp.re/image/2w1Y0g1O423h

> Tested with latest version 3.5.6

**Comment by ramiyahya** [comment]
I believe it's because JavaScript `Date` object are zero-indexed. It's on the documentation here. http://amsul.ca/pickadate.js/date/

**Comment by matthendrix** [comment]
ramiyahya is correct, I had the same issue.
