### ISSUE TITLE
Pickadate makes the screen scroll to the top on default Android browser and it doesn't come back after selecting the date

### ISSUE THREAD

**Issue by VaroLop** [amsul/pickadate.js#769]
Tested on a Samsung Galaxy S2 with Android 4.1.1
Tested also on pickadate website (examples and demos).

I open the picker and the page scrolls to top. Once I select a date, the picker closes but the scroll remains at the top of the page and the user loses the focus of the application form.

It works on newer versions of Android and in other browsers (such as Chrome).

Thanks in advance.

**Comment by rgksugan** [comment]
Facing the same issue on desktop browser as well.

**Comment by VaroLop** [comment]
The problem continues. Any idea?

**Comment by mortentrojborg** [comment]
This seems due to setting "overflow: hidden" on the html tag when the Picker opens.

	// Prevent the page from scrolling.
	if ( IS_DEFAULT_THEME ) {
	    $html.
	        css( 'overflow', 'hidden' ).
	        css( 'padding-right', '+=' + getScrollbarWidth() )
	}

I've replaced $html with $('body') which still prevents the page from scrolling, but will stop the page from scrolling to the top when the picker opens.

**Comment by zuizuihao** [comment]
wait for the answer.

**Comment by dfusionTownsend** [comment]
@mortentrojborg Thanks nice fix, this worked for me on pickadate.js v3.5.0
