### ISSUE TITLE
Date Picker not unfocusing correctly

### ISSUE THREAD

**Issue by isaachinman** [amsul/pickadate.js#770]
Hi there, there's a major issue with your implementation of pickadate. It does not unfocus correctly. Go to [your own docs](http://amsul.ca/pickadate.js/date/), open the Date Picker by clicking, click outside of the form (or click 'Close) to close the form. Now open a new tab, to go it, and come back to the original tab. The Date Picker will reopen itself. 

This does not happen if you click on something else on the page after closing the Date Picker - so clearly it's not unfocusing correctly.

**Comment by isaachinman** [comment]
Well for anyone looking for a fix, I came up with a quick CSS fix:

    .picker__holder {
	pointer-events: none;
    }
    .picker__wrap {
		pointer-events: auto;
    }

**Comment by max1011** [comment]
@isaachinman i came up with a working solution, i have the code u need to add, of course it's all written by me so it took a few hours to figure this thing out, it's a hack to make it work, i didn't actually change their code, i am sorry i didn't explain this code enough with comments , but give it a try , this worked for me, this is the [codepen](http://codepen.io/max1011/pen/JYWeJq?editors=011)
```javascript
$(function() {
  // change this to your own
  var $datePicker = $('.datepicker')
  var $input = $datePicker.pickadate()

  // Use the picker object directly.
  var picker = $input.pickadate('picker');
  var times = 0;
  var prevActiveElement;
  var original = $datePicker.get(0);

  $(window).on("blur", function(e) {
    prevActiveElement = document.activeElement.classList.contains('picker__holder') ? original : null;
  }).on("focus", function(e) {
    var theOrg = document.activeElement.classList.contains('picker__holder') ? original : null;
    console.log();
    if (theOrg == prevActiveElement && times > 0 && picker.get('open') == false) {
      // force close ASAP
      requestAnimationFrame(function() {
        picker.close();
      });
    }
    times=1;
  });

  $('input').on('focus', function(e) {
    prevActiveElement = document.activeElement.classList.contains('picker__holder') ? original : null;
  })
  picker.on('close',function() {
    prevActiveElement = null;
  })
});
```

**Comment by nightire** [comment]
@max1011 I've tried very similar thing (in a ember component), but I'm not use a `times` to tracking, actually I'm not sure why you use a `times`? I tried with your implementation, but it fails at the first time tab switching. After remove the `times` tracking, all is well.

**Comment by max1011** [comment]
@nightire it was for debugging initially but i didn't remove after i was done cause it will not harm anything, but if it causes a problem for you then remove it

**Comment by joltmode** [comment]
I went with a basic `blur` solution.

If you do not care about <kbd>Tab</kbd> support, you can simply add an `onClose` handler for corresponding picker where you blur the `$holder` (input):

```javascript
$('input.datepicker').pickadate({
    onClose : function()
    {
        this.$holder.blur();
    }
});
```

Though, if you do care about <kbd>Tab</kbd>, then you can store blurrable elements and blur them only if the window is blurred:

```javascript
var $blurWithWindow = $();
    
$(window).on('blur', function()
{
    $blurWithWindow.blur();
});

$('input.datepicker').pickadate({
    onStart : function()
    {
        $blurWithWindow = $blurWithWindow.add(this.$holder);
    }
});
```

While the other solution will break <kbd>Tab</tbd> support after the window has been changed, it still was sufficent fix for me.

**Comment by imaia** [comment]
Hey  isaachinman, your fix seems to work here. Thanks!

**Comment by ShaheensWeb** [comment]
isaachinman, thanks a lot elegant solution.

**Comment by sebastiansulinski** [comment]
Thanks @isaachinman - I thought it was just me going mad :)

**Comment by amsul** [comment]
Let's please keep conversations where they've already been started (with a simple search): https://github.com/amsul/pickadate.js/issues/160
