### ISSUE TITLE
Issues with Bootstrap 3

### ISSUE THREAD

**Issue by adrianmihalko** [amsul/pickadate.js#778]
1,
Day names are aligned to the left:
th text-align: left coming from bootstrap

<img width="986" alt="screenshot 2015-10-10 22 50 48" src="https://cloud.githubusercontent.com/assets/733361/10413249/4f11f45c-6fa2-11e5-9878-28c8b103eff5.png">

2, opening position 

Firefox: opens at the bottom-center of the window:

<img width="990" alt="screenshot 2015-10-10 23 00 03" src="https://cloud.githubusercontent.com/assets/733361/10413256/bb9be1fa-6fa2-11e5-92db-2f2e7d97eca6.png">

Safari, Chrome: opens at the center of the window

3,
On iPhone, when the datepicker pops up it's zoomed in. I must zoom out (pinch out), let me show this on the following two images:

Default:

![img_2074](https://cloud.githubusercontent.com/assets/733361/10413307/8109e9d6-6fa4-11e5-9eeb-bfecc30bc208.jpg)

Zoom out:

![img_2075](https://cloud.githubusercontent.com/assets/733361/10413310/8ef8f0b4-6fa4-11e5-90d8-d009de130645.jpg)

I think it is because If I click on input element it's zooming in by default.

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />`

This is working, but I loose zooming on the page.

**Comment by amsul** [comment]
These CSS issues are beyond the scope of this library. Also, won't be a problem in v5
