### ISSUE TITLE
Calendar is Blurry in Internet Explorer

### ISSUE THREAD

**Issue by FaiqH** [amsul/pickadate.js#794]
Title says is all.
![blurrycal](https://cloud.githubusercontent.com/assets/7585320/11159100/2e4b5d70-8a1a-11e5-87c9-72126786bfe8.png)

**Comment by FaiqH** [comment]
So far I have found that it is due to the transform css property. Any solutions to fix this without removing the animation?

**Comment by adedip** [comment]
I had the same problem, funny thing is, I had 2 instances in the same page, one in the page and one in the modal (I'm using zurb foundation), and only the popup one is blurry as the picture above.

**Comment by amsul** [comment]
Won't be a problem in v5
