### ISSUE TITLE
Fix for date input value "..." string.match is null

### ISSUE THREAD

**Issue by Code-Stars** [amsul/pickadate.js#796]
Hi developer,

I am using "..." as a default value at the pickadate field. This made the getFirstWordLength function to fail. So I added a check if string.match is not null. Hope you will push this little improvement through. :)

// line 663 picker.date.js
function getFirstWordLength( string ) {
     return string.match(/\w+/) != null ? string.match(/\w+/)[0].length : 0;
 }

**Comment by amsul** [comment]
Won't be a problem in v5
