### ISSUE TITLE
pickadate.get('view'); doesn't return correct data

### ISSUE THREAD

**Issue by benoittgt** [amsul/pickadate.js#799]
It seems the `picker.get('view')` is having problem.

Even on the documentation : http://amsul.ca/pickadate.js/api/#method-get-view if 

Everytime it returns : `2015/11/01`. Here a screenshot on my problem.

<img width="671" alt="capture d ecran 2015-11-25 a 11 49 29" src="https://cloud.githubusercontent.com/assets/8417720/11395432/546a669a-936b-11e5-9e75-30220d83e167.png">

Date I see is `2015/11/25`. Date I get with `datePicker.get('view', 'yyyy/mm/dd'); // "2015/11/01"`

**Comment by benoittgt** [comment]
I don't have the problem with the time. Only with date.

The bug can be reproduced on the documentation.

**Comment by benoittgt** [comment]
For the moment to avoid this issue. I have to parse the value from pickadate and format it with moment:

```javascript
var datePicker = $('#date-picker').pickadate('picker');
var date = moment(datePicker.get('value')).format('YYYY/MM/DD');
```

**Comment by benoittgt** [comment]
The problem is it work only with english date.  :(

**Comment by amsul** [comment]
You're looking for `select`, not `view`. Re-read the api docs 😉 : http://amsul.ca/pickadate.js/api/#method-get-select

**Comment by benoittgt** [comment]
Thanks @amsul
