### ISSUE TITLE
Add option to select starting day of week

### ISSUE THREAD

**Issue by runeb** [amsul/pickadate.js#8]
Our weeks start on monday

**Comment by ludal74** [comment]
Hi ! great job on this calendar component ! Realy beasy and fast to use. Thank you. It could be interesting to extend firstday parameter to choose any day of the week.

**Comment by svinesh3691** [comment]
@amsul  The page you have given [http://amsul.github.com/pickadate.js/docs.htm#first_day] is 404 now...!

**Comment by afarriaga** [comment]
Hi! Does anyone know what value should I set to get weeks to start on Monday?
