### ISSUE TITLE
Jquery - obtain 'format:' and not 'formatSubmit:' like .val()

### ISSUE THREAD

**Issue by pfloriginale** [amsul/pickadate.js#817]
My code

 $('#date').pickadate({
                format: 'dddd d mmmm yyyy',
                formatSubmit: 'yyyy-mm-dd',
 });

---

I want retrieve the value for display to current user but NOT in **formatSubmit** format

Whit..
var date  = $('input[name="date"]').val();
## I obtain **formatSubmit: 'yyyy-mm-dd'** format but I would like **format: 'dddd d mmmm yyyy',** format

Some help?
Thank a lot and a lot of  compliments!

**Comment by amsul** [comment]
`$('input[name="date_submit"]').val()` (I think)
