### ISSUE TITLE
Pickadate running on wordpress

### ISSUE THREAD

**Issue by ghost** [amsul/pickadate.js#826]
Hi guys, 

I'm new to WordPress and I'm looking to install this plugin.

I've tried automatically installing it using the WordPress inataller but having no luck

I also tried to manually install it through my cPanel but again no luck

Is pickadate compatible with WordPress ?

Cheers

**Comment by quantumleap33** [comment]
No, it's not, you will have to enqueue all picker javascript and css manually, google "How to Properly Add JavaScripts and Styles in WordPress". Then you will have to call the picker on an input field (could also be a custom field) like the examples on the homepage.
