### ISSUE TITLE
Jquery 2.2.1

### ISSUE THREAD

**Issue by samibn** [amsul/pickadate.js#841]
Hello Guys ,

After updating my jQuery to 2.2.1, date picker stop working .

Please help .

**Comment by littleguga** [comment]
+1
Last version of jquery with pickdate.js works is 2.1.4

**Comment by ercchy** [comment]
No news on this front?

**Comment by FrankSt** [comment]
+1

**Comment by czbaker** [comment]
This is still a problem.  I'm using Materialize (their datepicker is a modified version of pickadate.js), and I can't use any version of jQuery newer than 2.1.4.

Seems that it's silly to not fix this, being forced to use an old version of jQuery isn't exactly a good thing.
