### ISSUE TITLE
Cannot read property 'defaults`

### ISSUE THREAD

**Issue by ateregulov** [amsul/pickadate.js#854]
Uncaught TypeError: Cannot read property 'defaults' of undefined(anonymous function) @ ru_RU.js:1

**Comment by 4ndro1d** [comment]
Same here in de_DE, line 16

**Comment by 4ndro1d** [comment]
Looks like it is searching for pickatime values, which is not used

**Comment by claytongf** [comment]
Remove pickatime extension from the translation file that will work.

**Comment by CptMeatball** [comment]
That approach doesn't work when using a cdn like cdnjs or jsdelivr.

**Comment by DanielRuf** [comment]
We discourage using a CDN for privacy reasons. Either you mock `pickatime` and add it as empty object, you add it or you have to use modified files.

**Comment by teodorsandu** [comment]
translations should be on different files for pickadate/pickatime as they are different things and they could be used separately. Avoids an ugly, red error in the console

**Comment by DanielRuf** [comment]
Hi @teodorsandu,

We are aware of this.
v3 is in maintenance mode now, there will be no big changes.

You can test v5, it should be resolved there.

**Comment by teodorsandu** [comment]
hi @DanielRuf, thanks for lmk & sorry for bothering. And thanks for the library & your work!
