### ISSUE TITLE
Set a SelectYear from

### ISSUE THREAD

**Issue by waaromikniet** [amsul/pickadate.js#858]
Hi,

Is there a way I can show the selectyear drop down and set a start year. When I no set
selectYears: 10

I see 5 years in the past. I only want to show previous year and future years

Regards
Danny

**Comment by massic80** [comment]
#845 
#844

**Comment by waaromikniet** [comment]
Didn't see any updates and its 2 years old

**Comment by DanielRuf** [comment]
What about min and max settings?

**Comment by waaromikniet** [comment]
Its been a while but I think I used the min max setting indeed
