### ISSUE TITLE
Blank space under 'clear' button on pickatime

### ISSUE THREAD

**Issue by jtemporal** [amsul/pickadate.js#869]
Hi,

So I was wondering why there is this blank space under the `clear` button on pickatime. First I thought it was because I had `clear: '',` but then looking at the site, it is there even with the default config (like the image bellow).
 
![pickatime-screenshot](https://cloud.githubusercontent.com/assets/6595551/15189644/3a3fd3d6-1782-11e6-87a1-d26716599667.png)

There is anything we can do to make it vanish?

Thanks.

**Comment by Jivebunny** [comment]
Just change the following timepicker css that you're using (default.time.css perhaps) into:

.picker__list {
    list-style: none;
    padding: 0.75em 0 **4.2em**;
    margin: 0;
}

The padding is 4.2em bottom, change it to what you want.

**Comment by bl4ckdu5t** [comment]
@jtemporal did @Jivebunny 's solution work for you?

**Comment by jtemporal** [comment]
I'm not even working on the project that used the pickatime. =/

And I no longer have the project files to test it.

**Comment by amsul** [comment]
Feel free to make your own simple CSS changes..closing this
