### ISSUE TITLE
Error finding module using webpack/bower

### ISSUE THREAD

**Issue by oquis** [amsul/pickadate.js#870]
When trying to import the library I get the following error:

```
ERROR in ./bower_components/pickadate/lib/picker.date.js
Module not found: Error: Cannot resolve module 'picker' in /Users/jmrubio/react/mobile-react/bower_components/pickadate/lib
 @ ./bower_components/pickadate/lib/picker.date.js 10:8-47
```

Changing the import in `picker.date.js` seems to fix this issue for me:

``` javascript
/*!
 * Date picker for pickadate.js v3.5.6
 * http://amsul.github.io/pickadate.js/date.htm
 */

(function ( factory ) {

    // AMD.
    if ( typeof define == 'function' && define.amd )
        define( ['picker', 'jquery'], factory )

    // Node.js/browserify.
    else if ( typeof exports == 'object' )
        module.exports = factory( require('./picker.js'), require('jquery') )

    // Browser globals.
    else factory( Picker, jQuery )

}
```

change to:

``` javascript
/*!
 * Date picker for pickadate.js v3.5.6
 * http://amsul.github.io/pickadate.js/date.htm
 */

(function ( factory ) {

   module.exports = factory( require('./picker.js'), require('jquery') )

}
```

**Comment by oquis** [comment]
I solved this by adding an alias in webpack's config file:

```javascript
resolve: {
  alias: { 'picker': 'pickadate/lib/picker' }
}
```

I'm sure there's a better way of resolving this issue, but I have no idea how to do it right now

**Comment by uxweb** [comment]
@oquis @amsul 

I had the same issue trying to use it with webpack.

Is there a better way of solving it?.

Thanks for this amazing date&time picker, i use it an all my projects!, love it!

**Comment by jantimon** [comment]
We should just flip the amd and the commonjs loaders like this:

```js

/*!
 * Date picker for pickadate.js v3.5.6
 * http://amsul.github.io/pickadate.js/date.htm
 */

(function ( factory ) {

    // Node.js/browserify.
    if ( typeof exports == 'object' )
        module.exports = factory( require('./picker.js'), require('jquery') )
    // AMD.
    else if ( typeof define == 'function' && define.amd )
        define( ['picker', 'jquery'], factory )

    // Browser globals.
    else factory( Picker, jQuery )

}

```

So we keep everything as is but use the webpack commonjs loader (which will be able to resolve `require('./picker.js')`);

**Comment by japostigo-atsistemas** [comment]
Working fine with @oquis solution. Refer to https://stackoverflow.com/a/43917890/2940802 to extend webpack config for Ionic 3 or Angular 4 projects :)

**Comment by nonamez** [comment]
@oquis @japostigo-atsistemas can give a hint ho to use it after adding that `resolve` thing... Still cant import...

**Comment by DanielRuf** [comment]
@nonamez please provise a repl.it test or another test with test configs so we can reproduce and test this.

**Comment by DanielRuf** [comment]
Closing as this issue is very old and we did not receive further feedback.
