### ISSUE TITLE
DateTimePicker

### ISSUE THREAD

**Issue by paulux84** [amsul/pickadate.js#872]
Why you release a datePicker, a timePicker but not a dateTimePicker?

**Comment by macagua** [comment]
:+1: by this idea

**Comment by Jivebunny** [comment]
Because this makes for more flexible use of the library? It's easy enough to combine both...

**Comment by amsul** [comment]
Read the guidelines before opening an issue please: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md

This request has already come up several times.
