### ISSUE TITLE
Error when using gulp-concat

### ISSUE THREAD

**Issue by bahobab** [amsul/pickadate.js#873]
This error pops up in the browser console: "Uncaught ReferenceError: Picker is not defined"
The code runs fine when not using concatenation

The error points to the Picker variable in the //Browser globals section:

(function ( factory ) {

```
// AMD.
if ( typeof define == 'function' && define.amd )
    define( ['picker', 'jquery'], factory )

// Node.js/browserify.
else if ( typeof exports == 'object' )
    module.exports = factory( require('./picker.js'), require('jquery') )

// Browser globals.
else factory**( Picker**, jQuery )
```

}

**Comment by DaniloPolani** [comment]
+1

**Comment by DanielRuf** [comment]
The files are wrapped with UMD. You have to use `import` or `require`.
