### ISSUE TITLE
submit name, popup behaviour and margin bottom

### ISSUE THREAD

**Issue by topnew** [amsul/pickadate.js#874]
Hi Amsul,

Great scripts. Thanks!

But I got 3 issues:

1 - possible bug: when you click on a browser tab, show a webpage, when this page contains .pickadate and value not set, by default it will popup a pickadate dialog, which should be not.

2 - for some reason, the margin-bottom of pickadate dialog is not enough so that the last line is half outside the box

3 - if an input field name = mydate, onsubmit, i would expect $_POST['mydate'] not $_POST['mydate_submit']. is this an easy fix?

Thanks again.

**Comment by topnew** [comment]
Hi,

As per above #3, is it possible to swap $_POST['mydate'] with $_POST['mydate_submit']?

ie. pickadate will hide mydate, and store converted date into mydate,

while pickadate will show mydate_submit on screen according to user format?

**Comment by bl4ckdu5t** [comment]
If you need an extra bottom margin you can add it. pickadate wouldn't alter the name of your input so check that you're doing it right with your server-side language of choice. For Your 1, check that you don't have autofocus on in that input.
