### ISSUE TITLE
how to get the input value ??

### ISSUE THREAD

**Issue by moahmn** [amsul/pickadate.js#885]

**Comment by jakejarrett** [comment]
@moahmn You can get the date the same way you would any element, for example, lets say your element has an ID of date, here's a way you could get the value

```js
document.getElementById("date").value
```

**Comment by dbr0** [comment]
I'm strugling with this at the moment.

Why does this returns undefined?

$('#start_time,#end_time').pickatime({
                autoclose: true,
                twelvehour: false,
                afterDone: function(time) {
                    console.log('done');
                    console.log(time)
                }
            });

**Comment by bl4ckdu5t** [comment]
@dbr0 You could get the current value of the DOM element as said earlier by jake. There is no afterDone event. The events you have to work with are: `onStart`, `onRender`, `onOpen`, `onClose`, `onSet`, `onStop`. On that event you can query the element for its value
