### ISSUE TITLE
UTF-8 problem on set value

### ISSUE THREAD

**Issue by danieljausovec** [amsul/pickadate.js#893]
Hi.

I have problem on render pickadate with utf-8 characters (Slovenian language). Value not set correct.

Code example on start

```
<input name="my_date" class="my_date" value="Četrtek, 28 Julij 2016" />
<script>
$('.my_date').pickadate({
    format: 'dddd, dd mmmm yyyy',
});
<script>
```

If i set input value on "Cetrtek, 28 Julij 2016" works perfect. 
Is there any solution to this?

**Comment by amsul** [comment]
The character set is based on what you declare in your HTML code.
