### ISSUE TITLE
Unable to format initial value

### ISSUE THREAD

**Issue by imaia** [amsul/pickadate.js#906]
I have an input that, after an submit, it is re-rendered with a value which is "formatted" according to the backend framework. Because of that, I have to re-set the value of the calender to have it formated in the pickadate way. 
The problem is that it doesn't work. If set('highlight', value) is called from within onStart, I get a infinite loop. If done on onSet, nothing happens. If set with set('select', value), also, nothing happens. 
What should I do? (using materializecss)

[edit]
Actually, I'm unable to format the server response or an initial value. I expected pickadate to format the server response according to the "format" option. It actually leaves the value it finds within the input intact.

**Comment by JonaMX** [comment]
Hey @imaia I have exactly the same issue, did you find out a workaround to make it work?

**Comment by JonaMX** [comment]
I just made it work, there is an attribute named `data-value` that you should use for pre-fill the input, I used it as it's described in the [documentation](http://amsul.ca/pickadate.js/date/#formats_prefill) and everything worked as expected.

**Comment by bl4ckdu5t** [comment]
Good to know it worked for you @JonaMX
