### ISSUE TITLE
Ideas to make pickadate.js supports Islamic calendar?

### ISSUE THREAD

**Issue by MajidCS** [amsul/pickadate.js#909]
Hi there,

Anyone have ideas to support Islamic calendar

or 

Can you support in the next updates?

**moment-hijri.js**
https://github.com/xsoh/moment-hijri/blob/master/moment-hijri.js

I think it's feature needed by a large segment.

Thank you,

**Comment by bl4ckdu5t** [comment]
@MajidCS we do have an arabic [translation](https://github.com/amsul/pickadate.js/blob/master/lib/translations/ar.js) but you can send in a PR for what you're expecting
