### ISSUE TITLE
selectYears and selectMonths not working

### ISSUE THREAD

**Issue by gap06m** [amsul/pickadate.js#910]
Hi Amsul, 

I have recently downloaded your pickadate.js and implemented it on my project. It was very nice! however, I'm having difficulty with the selectYears and selectMonths options. It should be pretty straight forward tight? But for some odd reason it doesn't show any selectors at all. I'm developing on XAMPP windows using PHP and AngularJS Hope you can help me about this. Thanks!

**Comment by gap06m** [comment]
![pickadatenoselectors](https://cloud.githubusercontent.com/assets/9815770/18209676/670b2a52-7167-11e6-9ba3-f9603127f11e.jpg)

`app.controller("homeController", function($scope) {	

	$('.datepicker').pickadate({  		
	  	selectMonths: true,
	  	selectYears: true  	
	});
 		
});`

**Comment by amsul** [comment]
Read the guidelines before opening a new issue: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md. Please create a reproducible reduced test case first.

It clearly works here: http://amsul.ca/pickadate.js/date/#selectors. There is probably something else wrong in your application.
