### ISSUE TITLE
Georgian language pack

### ISSUE THREAD

**Issue by ShavidzeT** [amsul/pickadate.js#913]
Can I contribute this repository?
I want to add Georgian language pack

**Comment by bl4ckdu5t** [comment]
Hi @ShavidzeT you're free to send a PR. Just ensure you run the test and they pass. If the tests are okay they'll be pulled in

**Comment by ShavidzeT** [comment]
Thank you, of course tests should be passed :)

**Comment by ShavidzeT** [comment]
Please checkout https://github.com/amsul/pickadate.js/pull/914

**Comment by bl4ckdu5t** [comment]
@ShavidzeT PR merged
