### ISSUE TITLE
Tabs changing (BUG)

### ISSUE THREAD

**Issue by Dimasion** [amsul/pickadate.js#915]
Hello Amsul,

I found a bug in TimePicker. Close the TimePicker, go to another tab in your browser, and then come back and see - TimePicker reopened.

Could you help solve this problem? I am very grateful for the perfect Picker.

**Comment by amsul** [comment]
Please do a search before posting the same issues: https://github.com/amsul/pickadate.js/issues/160

https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports
