### ISSUE TITLE
double click date in small screen

### ISSUE THREAD

**Issue by moahmn** [amsul/pickadate.js#926]
i use classic theme,and i use bootstrap, if i change my screen to 1280 * 1024 or 1366 * 768 . when the modal opened, i try to change year selector ,and then  i click date,but i need to click double then it can be selected? that why? in 1920 * 1024 is work well

**Comment by moahmn** [comment]
i fixed this problem! i set  height and overflow attr,if modal open,it just show a little,not complete,the problem will happen,and i try to binding event when modal is opened,and scroll to div height,and the problem fixed!!

**Comment by amsul** [comment]
Read the guidelines before opening a new issue: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md

This does not belong on Github, but on StackOverflow
