### ISSUE TITLE
Is it allowed to use jQuery elements for the container setting?

### ISSUE THREAD

**Issue by naBausch** [amsul/pickadate.js#927]
hey @amsul we need a quick feedback

In your documentation you state at the following page:
http://amsul.ca/pickadate.js/date/#container
https://github.com/amsul/pickadate.js/blob/gh-pages/date.html#L608

That `"by passing any valid CSS selector to this option"` however because we have multiple pick a date instances and therefore multiple `container` elements we need sth like:

```js
$('.datepicker').each(function() {
  var $picker = $(this);  
  $picker.pickadate({
    container: $picker.find('.container')
  });
});
```

This works perfectly because you pass the container option through jquery:

https://github.com/amsul/pickadate.js/blob/master/lib/picker.js#L130
```js
if ( SETTINGS.container ) $( SETTINGS.container ).append( P.$root )
```

Now we need you because @theodorejb won't let us merge [DefinitelyTyped #11881](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11881) because he says that using a jQuery selector is not intended by you.

Do you think that is a valid case and could we change the documentation?

We really need [DefinitelyTyped #11881](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11881) for our current project.

**Comment by amsul** [comment]
@naBausch responded: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11881#issuecomment-253940879

Totally fine with this...I'll update the docs to reflect it 👍

**Comment by jantimon** [comment]
Thanks amsul :)

**Comment by naBausch** [comment]
Thank you very much :)
