### ISSUE TITLE
Using Yarn vs. npm install

### ISSUE THREAD

**Issue by SimonJ** [amsul/pickadate.js#932]
Hey guys,

I'm I the only one having issues when using Yarn instead of `nom install` ? 
when i run `npm install` pickadate, works fine. but if I run `yarn install` it says pickadate is not a function :S

**Comment by crudo** [comment]
@SimonJ the same problem here.

**Comment by SimonJ** [comment]
hmm anyone else have same issue?

**Comment by bl4ckdu5t** [comment]
@SimonJ can you explain how you landed at this error. I just did a `yarn add pickadate` and that worked fine

**Comment by joepagan** [comment]
I just ran `yarn add pickadate`, it went into my `package.json` but not into `node_modules` directory. Couldn't get it to appear by following up with a `yarn install` either. Had to npm install it.
