### ISSUE TITLE
HI, in the doc min and max exemple with new date

### ISSUE THREAD

**Issue by studio42** [amsul/pickadate.js#934]
min: new Date(2015,3,20),
  max: new Date(2015,7,14)
is wrong format and give not right date(see date javascript explains)
  min: new Date("2015-03-20"),
  max: new Date("2015-07-14")
Is right and set for any date right result.
Simply try something as new Date(2016,12,20), or  Date(2017,1,7) and check the result
console.log(new Date(2016,12,20))

> Fri Jan 20 2017 00:00:00 GMT+0100 (Paris, Madrid)
> console.log(new Date(2017,01,20))
> Mon Feb 20 2017 00:00:00 GMT+0100 (Paris, Madrid)

**Comment by DanielRuf** [comment]
The `Date` API in browsers is 0 indexed, try `new Date(2015,2,20)`

**Comment by studio42** [comment]
API in browsers is 0 indexed ???
Date(2016,12,20) >> Fri Jan 20 2017 ???
The only clean way is how i explained

**Comment by DanielRuf** [comment]
Yes, the months start with 0. 0 is January. 12 produces an overflow and also January. 11 is December. 13 is February.

**Comment by JonathanSchndr** [comment]
Sorry @DanielRuf .. but WHY? 0 = January
And is 0 = January in disabled days also?

**Comment by DanielRuf** [comment]
@JonathanSchndr can you clarify what you mean? I think you mean different things.

**Comment by DanielRuf** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

https://amsul.ca/pickadate.js/api/#item-objects
> // The month with zero-as-index.

https://amsul.ca/pickadate.js/date/

In general 3 is always April as expected in JavaScript.

**Comment by DanielRuf** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

> The getMonth() method returns the month in the specified date according to local time, as a zero-based value (where zero indicates the first month of the year).

https://amsul.ca/pickadate.js/api/#item-objects
> // The month with zero-as-index.

https://amsul.ca/pickadate.js/date/

In general 3 is always April as expected in JavaScript.

**Comment by DanielRuf** [comment]
For further questions please open a new issue.

**Comment by JonathanSchndr** [comment]
Thanks @DanielRuf  for the sources, I got it now!
