### ISSUE TITLE
Showing wrong date in iPhone and iPad devices

### ISSUE THREAD

**Issue by debash009** [amsul/pickadate.js#939]
I have used the plugin in woocommerce platform. Please visit https://www.indiadresswala.com/product/apple/. When we choose the start date the end date should be 4 days+ from the current date. For an example suppose I am choosing 22nd December as a start date the end date will be 25th December. 

The end date showing the current date it is not changing respective of the current date. The other devices is working fine. Please suggest what is the exact issue.

**Comment by amsul** [comment]
Please follow the bug report guide: https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md#bug-reports
