### ISSUE TITLE
set default as "today"

### ISSUE THREAD

**Issue by tolchai** [amsul/pickadate.js#94]
Hi,
just a small question: Is there a way I can set "today" as a default value after DOM is ready?

Thanks!

**Comment by rijk** [comment]
@amsul This triggers the `onSet` handler.. Is there another way to set the initial value?

**Comment by neurotik1** [comment]
If anyone else has the same question as @rijk, just pass {muted: true} as the third parameter in the set function (options).

**Comment by tympaaz** [comment]
I had to remove +1 from `date.getMonth()` to get current month
`this.set('select', [date.getFullYear(), date.getMonth(), date.getDate()]);`

**Comment by akkiyash** [comment]
Iam not able to set the current date in the textbox using pickadate..
Can anyone please explain how to do it.

**Comment by abhilash2006** [comment]
Please give a solution for setting the current date by default

**Comment by mepsd** [comment]
the simplest method is 
` onStart: function() {
        this.set({ select: new Date()});
      }`
give this a try
