### ISSUE TITLE
Disable time range 8am to 9am every Friday

### ISSUE THREAD

**Issue by bkmorse** [amsul/pickadate.js#965]
I am looking thru the documentation and I am unsure if this is possible.

I am using the pickadate and pickatime. I want the ability to disable the time range 8am to 9am for every Friday.

**Comment by bkmorse** [comment]
Would I need to use one of the methods to see what date they selected and then disable that 8am-9am time slot, using the disable method for pickatime?

**Comment by edwardjiang7** [comment]
If your date picker is an input box, you can get the value of the date input and then use an if statement.

Something like this will work:

```
var date_input = document.getElementById('date-input').value;
var d = new Date(date_input);
var day = d.getDay()

if(day == 5) {
    // Call the pickatime function and set the disabled times
}
```
