### ISSUE TITLE
Better month & year selector

### ISSUE THREAD

**Issue by aungzanbaw** [amsul/pickadate.js#97]
I am plan to use for user's DOB
it obliviously need to click dozen of click to reach their birthday
Are there any plans to implement for following ?

Date  & Year (drop down) or 

Can we do 
            $( '#dob_profile' ).pickadate({
                format: 'yyyy-mm-dd',
                dateMax:true
                startMonth: 'March'
                startYear: '1997'  
            });   // ( all customer must above 16 )
   then it would be ready to use as soon as customer focus on input 

Thanks for your brilliant pickadate

**Comment by Aniket-ajency** [comment]
Hello,
I am new to this calendar and just trying to use it in my mobile app. Can we show three months at a time using this calendar as I have to select a long dates.

**Comment by chrise86** [comment]
The codepen doesn't seem to work any more, any ideas?
