### ISSUE TITLE
Unable to pick multiple date 

### ISSUE THREAD

**Issue by xwenc** [amsul/pickadate.js#970]
Hello :)

I'm using pickdate on our quote page, i can't find a way to pick multiple date,
pls help me

**Comment by bl4ckdu5t** [comment]
You'd have to produce a reduced test case according to [this](https://github.com/amsul/pickadate.js#bugs) and [the contributing guide](https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md)
