### ISSUE TITLE
Cannot set format of date

### ISSUE THREAD

**Issue by djpero** [amsul/pickadate.js#974]
I can't set any format to datepicker, event submited, its always 

> 1 January, 2017

Any suggestion, thanks!

Here is a code: 

        var date_from = $('#date_from').pickadate({
            format: 'mm/dd/yyyy',
            formatSubmit: 'mm/dd/yyyy',
            selectYears: true,
            selectMonths: true
        });
        
        var picker_from = $('#date_from').pickadate('picker');
        picker_from.set('select', new Date(date.getFullYear(), 0, 1), {format: 'mm/dd/yyyy' });

**Comment by djpero** [comment]
It was my mistake, It was previously initialised.

**Comment by zeeshan4971** [comment]
@djpero  how did you fixed it i am having the same problem
