### ISSUE TITLE
padding on year month selector

### ISSUE THREAD

**Issue by migliori** [amsul/pickadate.js#984]
Hi,
Thanks for your great pickadate.
Just a small css issue : years & month labels in dropdown lists classic theme are cropped by vertical padding.

Solution is to remove vertical padding : 
`.picker__select--month,
.picker__select--year {
  border: 1px solid #b7b7b7;
  height: 2em;
  padding: 0 .5em;`
}

**Comment by bl4ckdu5t** [comment]
@migliori You've been able to solve this with that?

**Comment by migliori** [comment]
Yes, just removed the vertical padding. Nothing more.

**Comment by bl4ckdu5t** [comment]
Thank you. The next version does not have the same problem. This would be referenced for anyone else with such issue on this version
