### ISSUE TITLE
Calendar Aways Visible

### ISSUE THREAD

**Issue by marcosstefani** [amsul/pickadate.js#990]
Hi!
Firstly, I would like to thank and congratulate you for this spectacular calendar. I have used it frequently and I am very satisfied. However, there was a need to leave the calendar displaying after it was opened. I really do not want to use another just because of this need, but I'm not able to leave it open, I would need it to have some property that when passing it does not allow clicking on it outside the calendar it closes, just as it has the property of no Close when you select.

**Comment by marcossrosa** [comment]
If you can, thank you.
![image](https://cloud.githubusercontent.com/assets/16294901/26357624/3dd89e2c-3fa6-11e7-9681-ff63605cdbee.png)
![image](https://cloud.githubusercontent.com/assets/16294901/26357638/4cc482d4-3fa6-11e7-8c14-3d86a4546622.png)

**Comment by NetOperatorWibby** [comment]
I've solved this issue with CSS. Simply put the styling on `.picker__holder` inside of `.picker`. Here's my code (using Sass):

```
.picker {
  color: $black;
  float: left;
  font-size: 16px;
  height: 25rem;
  line-height: 1.2;
  position: relative;
  text-align: left;
  user-select: none;

  &:first-of-type {
    width: 80%;
  }

  &:last-of-type {
    width: 20%;
  }

  // this makes the picker appear all the time
  .picker__holder {
    max-height: 25rem;
    opacity: 1;
    transform: translateY(0) perspective(600px) rotateX(0);
  }
}
```

Please note that I have custom styling in here for my own project.
